### ISSUE TITLE
怎么抓包呢

### ISSUE THREAD

**Issue by zdeicn** [insoxin/China-Telecom-Helper#1]
para是什么
怎么抓包吖

**Comment by insoxin** [comment]
你好,在app 我 的页面,点进去签到领取任何一任务奖励都能抓到post 参数 para

有时间 我可能会更新下详细教程,

**Comment by zdeicn** [comment]
> 你，在app我的页面，点进去签到的任何一个任务奖励领取到领取奖励
> 
> 有时间我可能会更新下详细的教程，

快点出个教程吧，不知道para是哪段

**Comment by hhdong** [comment]
para有具体示例吗，是否考虑开源

**Comment by insoxin** [comment]
> > 你，在app我的页面，点进去签到的任何一个任务奖励领取到领取奖励
> > 有时间我可能会更新下详细的教程，
> 
> 快点出个教程吧，不知道para是哪段

![image](https://user-images.githubusercontent.com/19371836/168962677-7d24d4d2-0ec5-4e8c-ae6d-af0fac4c4688.png)
这是朋友安卓下小黄鸟的抓包,我iOS thor抓包 是在消息体内
![1FBC18D75AFA7C3771EDDD8B648D3725](https://user-images.githubusercontent.com/19371836/168962785-ca4b7e94-54fc-4e5b-a2f5-ff2fd99c1e64.png)

**Comment by insoxin** [comment]
> para有具体示例吗，是否考虑开源
![image](https://user-images.githubusercontent.com/19371836/168962909-60c6f59f-b5db-4bd5-9422-d2b4dd79e4cb.png)

还没完善,有功能还没加上,不忙的话近期会出0.2版本修一部分bug 和新功能

**Comment by zdeicn** [comment]
现在做任务是返回成功，实际是没做，期待更新。感谢

**Comment by insoxin** [comment]
> 现在做任务是返回成功，实际是没做，期待更新。感谢

对的有人反馈这个bug了我多号抓包对比,才发现每个人的每个任务链接都不一样

**Comment by zdeicn** [comment]
> > 现在做任务是返回成功，实际是没做，期待更新。
> 
> 对的某人反馈这个虫子让我多抓包对比，才发现每个人的每个任务链接都不一样

嗯，有时间更新下吧，刚学会抓包。投食任务是正常的，其他奖励任务错误

**Comment by fengphhhhh** [comment]
para好像不是固定的，通过加密生成的
只有喂食成功了

**Comment by zdeicn** [comment]
> > 现在做任务是返回成功，实际是没做，期待更新。感谢
> 
> 对的有人反馈这个bug了我多号抓包对比,才发现每个人的每个任务链接都不一样

大佬给个WIN版啊。Linux搞不好

**Comment by zdeicn** [comment]
> 

好的，谢谢谢

**Comment by insoxin** [comment]
> > 
> 
> 好的，谢谢谢

https://github.com/insoxin/China-Telecom-Helper/releases/tag/v0.2 上传了,测试测试, 写了使用教程https://github.com/insoxin/China-Telecom-Helper/wiki

**Comment by insoxin** [comment]
> > 
> 
> 给个交流群吧大佬，大家可以交流下，这样自行摸索搞不懂啊

这改不够详细么  啊这啊这,我本来就写了二十字.硬生生水了那么多字,哪里遇到问题了,我再补充补充

**Comment by insoxin** [comment]
@[zdeicn](https://github.com/zdeicn) 配置没错,我也遇到过,是电信那边出问题了,正常访问也加载不出来,让我想想办法

**Comment by insoxin** [comment]
每天执行多次?

**Comment by zdeicn** [comment]
> @[zdeicn](https://github.com/zdeicn) 配置没错,我也遇到过,是电信那边出问题了,正常访问也加载不出来,让我想想办法

难搞，抓了半天，执行不下于5次了

**Comment by insoxin** [comment]
![image](https://user-images.githubusercontent.com/19371836/169059473-97ef75c3-c32b-422b-a4fd-fd9f512a3555.png)
这是我去年参与的另一个项目,

**Comment by zdeicn** [comment]
![image](https://user-images.githubusercontent.com/104246494/169059711-5a884940-443f-4835-93f2-1bfc798b7866.png)
每次这里返回都是空

**Comment by insoxin** [comment]
> ![image](https://user-images.githubusercontent.com/104246494/169059711-5a884940-443f-4835-93f2-1bfc798b7866.png) 每次这里返回都是空

这没办法啊,不是我能控制的

**Comment by zdeicn** [comment]
> > ![image](https://user-images.githubusercontent.com/104246494/169059711-5a884940-443f-4835-93f2-1bfc798b7866.png) 每次这里返回都是空
> 
> 这没办法啊,不是我能控制的

难搞哦

**Comment by wcn666** [comment]
但是每执行一次不都是会消耗豆子吗？喂食任务> 每天执行多次?

**Comment by insoxin** [comment]
> 但是每执行一次不都是会消耗豆子吗？喂食任务> 每天执行多次?

活动规则看下啊

**Comment by tslace** [comment]
我也是可以成功喂食，但就是抓的几个任务都不做。另外问下大佬，教程里写的是抓https://wapside.189.cn这个网址下的，但我抓到的几乎都https://wapact.189.cn里的oYid6CPr，是否会有影响呢？
我是安卓12，最新版APP。

**Comment by insoxin** [comment]
> 我也是可以成功喂食，但就是抓的几个任务都不做。另外问下大佬，教程里写的是抓[https://wapside.189.cn这个网址下的，但我抓到的几乎都https://wapact.189.cn里的oYid6CPr，是否会有影响呢？](https://wapside.189.cn%E8%BF%99%E4%B8%AA%E7%BD%91%E5%9D%80%E4%B8%8B%E7%9A%84%EF%BC%8C%E4%BD%86%E6%88%91%E6%8A%93%E5%88%B0%E7%9A%84%E5%87%A0%E4%B9%8E%E9%83%BDhttps://wapact.189.cn%E9%87%8C%E7%9A%84oYid6CPr%EF%BC%8C%E6%98%AF%E5%90%A6%E4%BC%9A%E6%9C%89%E5%BD%B1%E5%93%8D%E5%91%A2%EF%BC%9F) 我是安卓12，最新版APP。

只有这个https://wapside.189.cn:9001/jt-sign/paradise/polymerize?oYid6CPr=很长一串

你抓的时候需要手动做下这个任务,然后抓包记录找这个链接,还要看返回值.我再去补充一下详细教程
