### ISSUE TITLE
建议定制一个 网上国网 电费签到脚本。

### ISSUE THREAD

**Issue by superxiaogui** [insoxin/China-Telecom-Helper#100]
建议定制一个 网上国网 电费签到脚本。
兑换电费。

**Comment by insoxin** [comment]
这个我很早就挂了,但是没必要,不够浪费电费的

50金币可以兑换0.2电费

0.2电费 ÷ 50金币 = 0.004电费/金币

45金币/周 × 4周/月 = 180金币/月

180金币 × 0.004电费/金币 = 0.72电费

一个月的签到可以兑换0.72电费,挂一个月,一块钱都不给,还有这么抠的没

**Comment by smallfawn** [comment]
脚本呢

**Comment by haohao232323** [comment]
> 这个我很早就挂了,但是没必要,不够浪费电费的
> 
> 50金币可以兑换0.2电费
> 
> 0.2电费 ÷ 50金币 = 0.004电费/金币
> 
> 45金币/周 × 4周/月 = 180金币/月
> 
> 180金币 × 0.004电费/金币 = 0.72电费
> 
> 一个月的签到可以兑换0.72电费,挂一个月,一块钱都不给,还有这么抠的没

现在还有抽奖，希望能在脚本加入抽奖，主要本身青龙也是挂着的，再增加这个脚本的电量损耗可以忽略

**Comment by sidesand** [comment]
> 这个我很早就挂了,但是没必要,不够浪费电费的
> 
> 50金币可以兑换0.2电费
> 
> 0.2电费 ÷ 50金币 = 0.004电费/金币
> 
> 45金币/周 × 4周/月 = 180金币/月
> 
> 180金币 × 0.004电费/金币 = 0.72电费
> 
> 一个月的签到可以兑换0.72电费,挂一个月,一块钱都不给,还有这么抠的没

能否共享一下网上国网签到脚本，感谢！
