### ISSUE TITLE
输入验证码后没用

### ISSUE THREAD

**Issue by wxhbts** [insoxin/China-Telecom-Helper#101]
一直请重新获取验证码

**Comment by insoxin** [comment]
不看文档,就自己抓包解决

**Comment by wxhbts** [comment]
说明同时登陆的人太多了？

**Comment by insoxin** [comment]
https://github.com/insoxin/China-Telecom-Helper/wiki/%E4%B8%80%E4%BA%9B%E6%95%B0%E6%8D%AE%E5%80%BC%E7%9A%84%E6%8A%93%E5%8C%85%E6%95%99%E7%A8%8B


更新了抓包教程,你应该需要
