### ISSUE TITLE
Unmarshal:  json: cannot unmarshal number 13800138000 into Go struct field User.users.phone of type int

### ISSUE THREAD

**Issue by maech01** [insoxin/China-Telecom-Helper#104]
Unmarshal:  json: cannot unmarshal number 13800138000 into Go struct field User.users.phone of type int
这个什么错误呢？zerotermux运行的

**Comment by insoxin** [comment]
贴配置文件,记得打码

**Comment by insoxin** [comment]
不回就关闭了

**Comment by maech01** [comment]
> 贴配置文件,记得打码

{
	"users": [{
		"AutoUpdate": "false",
		"systime": "http://cloudflare.api.isoyu.com/time/SysTime/?appCode=B586A14C4EC466D33682F8626CCB3794&auturl=api.isoyu.com&num=13",
		"Authorization": "false",
		"alipay": "",
		"sign": "9682947c194e4989a199dc30321ea143",
		"ua": "",
		"Monthlybeans": "",
		"cookie": "cookie",
		"Notice": "https://t.me/ChinaTelecomHelper",
		"phone": 19143458325,
		"para": [{
			"setting": "true"
		}, {
			"para156": ""
		}, {
			"para256": ""
		}, {
			"para768": ""
		}],
		"Paradise": [{
			"Polymerize": ""
		}, {
			"Polymerize": ""
		}, {
			"Polymerize": ""
		}]
	}]
}

**Comment by insoxin** [comment]
手机号漏了,给你删了

**Comment by maech01** [comment]
> 手机号漏了,给你删了

我改手机号和sign了

**Comment by insoxin** [comment]
> > 手机号漏了,给你删了
> 
> 我改手机号和sign了

那再重发一遍吧,我刚没细看

**Comment by maech01** [comment]
> > > 手机号漏了,给你删了
> > 
> > 
> > 我改手机号和sign了
> 
> 那再重发一遍吧,我刚没细看

{
	"users": [{
		"AutoUpdate": "false",
		"systime": "http://cloudflare.api.isoyu.com/time/SysTime/?appCode=B586A14C4EC466D33682F8626CCB3794&auturl=api.isoyu.com&num=13",
		"Authorization": "false",
		"alipay": "",
		"sign": "9682947c194e4989a199dc30321ea143",
		"ua": "",
		"Monthlybeans": "",
		"cookie": "cookie",
		"Notice": "https://t.me/ChinaTelecomHelper",
		"phone": 19143458325,
		"para": [{
			"setting": "true"
		}, {
			"para156": ""
		}, {
			"para256": ""
		}, {
			"para768": ""
		}],
		"Paradise": [{
			"Polymerize": ""
		}, {
			"Polymerize": ""
		}, {
			"Polymerize": ""
		}]
	}]
}

**Comment by maech01** [comment]
1.07可以正常运行.1.08后就不可以了

**Comment by maech01** [comment]
cd ~ && mkdir Telecom && cd /root/Telecom && wget -O config.json https://raw.githubusercontents.com/insoxin/China-Telecom-Helper/main/config.json && wget https://ghproxy.com/https://github.com/insoxin/China-Telecom-Helper/releases/download/1.0.9/China-Telecom-Helper_linux_arm.tar.gz && tar -xvzf China-Telecom-Helper_linux_arm.tar.gz&& chmod +x China-Telecom-Helper_linux_arm && ./China-Telecom-Helper_linux_arm
按这个安装的

**Comment by insoxin** [comment]
> 1.07可以正常运行.1.08后就不可以了

稍等,吃过饭,我测试一下

**Comment by insoxin** [comment]
> {
> "users": [{
> "AutoUpdate": "false",
> "systime": "http://cloudflare.api.isoyu.com/time/SysTime/?appCode=B586A14C4EC466D33682F8626CCB3794&auturl=api.isoyu.com&num=13",
> "Authorization": "false",
> "alipay": "",
> "sign": "9682947c194e4989a199dc30321ea143",
> "ua": "",
> "Monthlybeans": "",
> "cookie": "cookie",
> "Notice": "https://t.me/ChinaTelecomHelper",
> "phone": 19143458325,
> "para": [{
> "setting": "true"
> }, {
> "para156": ""
> }, {
> "para256": ""
> }, {
> "para768": ""
> }],
> "Paradise": [{
> "Polymerize": ""
> }, {
> "Polymerize": ""
> }, {
> "Polymerize": ""
> }]
> }]
> }

我测试了一下正常啊,你再试下

**Comment by maech01** [comment]
> 

China-Telecom-Helper_linux_arm/
China-Telecom-Helper_linux_arm/RSA/
China-Telecom-Helper_linux_arm/RSA/CHINATEL.RSA
China-Telecom-Helper_linux_arm/RSA/CHINATEL.SF
China-Telecom-Helper_linux_arm/config.json
China-Telecom-Helper_linux_arm/China-Telecom-Helper_linux_arm
bash: ./China-Telecom-Helper_linux_arm: Is a directory
root@localhost:~/Telecom $ ./China-Telecom-Helper_linux_arm/China-Telecom-Helper_linux_arm
Unmarshal:  json: cannot unmarshal number 13800138000 into Go struct field User.users.phone of type int
root@localhost:~/Telecom $

**Comment by insoxin** [comment]
> > 
> 
> China-Telecom-Helper_linux_arm/ China-Telecom-Helper_linux_arm/RSA/ China-Telecom-Helper_linux_arm/RSA/CHINATEL.RSA China-Telecom-Helper_linux_arm/RSA/CHINATEL.SF China-Telecom-Helper_linux_arm/config.json China-Telecom-Helper_linux_arm/China-Telecom-Helper_linux_arm bash: ./China-Telecom-Helper_linux_arm: Is a directory root@localhost:~/Telecom $ ./China-Telecom-Helper_linux_arm/China-Telecom-Helper_linux_arm Unmarshal: json: cannot unmarshal number 13800138000 into Go struct field User.users.phone of type int root@localhost:~/Telecom $

你是不是配置文件没改?你发我的是191,这个报错的138

**Comment by maech01** [comment]
> > > 
> > 
> > 
> > China-Telecom-Helper_linux_arm/ China-Telecom-Helper_linux_arm/RSA/ China-Telecom-Helper_linux_arm/RSA/CHINATEL.RSA China-Telecom-Helper_linux_arm/RSA/CHINATEL.SF China-Telecom-Helper_linux_arm/config.json China-Telecom-Helper_linux_arm/China-Telecom-Helper_linux_arm bash: ./China-Telecom-Helper_linux_arm: Is a directory root@localhost:~/Telecom $ ./China-Telecom-Helper_linux_arm/China-Telecom-Helper_linux_arm Unmarshal: json: cannot unmarshal number 13800138000 into Go struct field User.users.phone of type int root@localhost:~/Telecom $
> 
> 你是不是配置文件没改?你发我的是191,这个报错的138

改了，出来只是号码变了

**Comment by maech01** [comment]
China-Telecom-Helper_linux_arm/
China-Telecom-Helper_linux_arm/RSA/
China-Telecom-Helper_linux_arm/RSA/CHINATEL.RSA
China-Telecom-Helper_linux_arm/RSA/CHINATEL.SF
China-Telecom-Helper_linux_arm/config.json
China-Telecom-Helper_linux_arm/China-Telecom-Helper_linux_arm
bash: ./China-Telecom-Helper_linux_arm: Is a directory
root@localhost:~/Telecom $ ./China-Telecom-Helper_linux_arm/China-Telecom-Helper_linux_arm
Unmarshal:  json: cannot unmarshal number 13800138000 into Go struct field User.users.phone of type int
root@localhost:~/Telecom $ ./China-Telecom-Helper_linux_arm/China-Telecom-Helper_linux_arm
Unmarshal:  json: cannot unmarshal number 19142948335 into Go struct field User.users.phone of type int
root@localhost:~/Telecom $

**Comment by insoxin** [comment]
cd China-Telecom-Helper_linux_arm

./China-Telecom-Helper_linux_arm


你没在文件夹内执行

**Comment by insoxin** [comment]
> 1.07可以正常运行.1.08后就不可以了

我貌似找到了原因08以后版本压缩包,我打包进去了配置文件,和之前的方式不同,你CD进去文件夹 然后执行二进制就行了

**Comment by maech01** [comment]
> 

root@localhost:~/Telecom $ cd /China-Telecom-Helper_linux_arm
bash: cd: /China-Telecom-Helper_linux_arm: No such file or directory
root@localhost:~/Telecom $ cd
root@localhost:~ $ cd /root/Telecom/China-Telecom-Helper_linux_arm
root@localhost:~/Telecom/China-Telecom-Helper_linux_arm $ ./China-Telecom-Helper_linux_arm
Unmarshal:  json: cannot unmarshal number 13800138000 into Go struct field User.users.phone of type int
root@localhost:~/Telecom/China-Telecom-Helper_linux_arm $
cd进文件夹了还是一样，我把文件复制出来试过也提示这样

**Comment by insoxin** [comment]
> root@localhost:~/Telecom $ cd /China-Telecom-Helper_linux_arm bash: cd: /China-Telecom-Helper_linux_arm: No such file or directory root@localhost:~/Telecom $ cd
> root@localhost:~ $ cd /root/Telecom/China-Telecom-Helper_linux_arm
> root@localhost:~/Telecom/China-Telecom-Helper_linux_arm $ ./China-Telecom-Helper_linux_arm Unmarshal: json: cannot unmarshal number 13800138000 into Go struct field User.users.phone of type int root@localhost:~/Telecom/China-Telecom-Helper_linux_arm $
> 


默认的配置文件你能运行吗？

**Comment by insoxin** [comment]
因为我拿你的配置文件,运行是没错的,手里没有arm设备,如果你有amd的设备,试试看相同配置是否可以.

**Comment by maech01** [comment]
> > root@localhost:~/Telecom $ cd /China-Telecom-Helper_linux_arm bash: cd: /China-Telecom-Helper_linux_arm: No such file or directory root@localhost:~/Telecom $ cd
> > root@localhost:~ $ cd /root/Telecom/China-Telecom-Helper_linux_arm
> > root@localhost:~/Telecom/China-Telecom-Helper_linux_arm $ ./China-Telecom-Helper_linux_arm Unmarshal: json: cannot unmarshal number 13800138000 into Go struct field User.users.phone of type int root@localhost:~/Telecom/China-Telecom-Helper_linux_arm $
> 
> 默认的配置文件你能运行吗？

这个就是默认文件运行出来的，加上sign和号码出来也一样

**Comment by maech01** [comment]
> 因为我拿你的配置文件,运行是没错的,手里没有arm设备,如果你有amd的设备,试试看相同配置是否可以.

没有amd的设备😂

**Comment by insoxin** [comment]
> > 因为我拿你的配置文件,运行是没错的,手里没有arm设备,如果你有amd的设备,试试看相同配置是否可以.
> 
> 没有amd的设备😂

那只能先搁置了,报错信息判断是读取配置文件出错,但是你发我的配置文件,我可以运行,不知道从何排错……你有电脑吗？试试电脑运行相同配置

**Comment by maech01** [comment]
> > 因为我拿你的配置文件,运行是没错的,手里没有arm设备,如果你有amd的设备,试试看相同配置是否可以.
> 
> 没有amd的设备😂

![Screenshot_20230309_135338_com termux_edit_261892862411599](https://user-images.githubusercontent.com/70949690/223933251-211d9203-cd63-4dcf-961d-97637a9f1712.jpg)

**Comment by insoxin** [comment]
图片手机号没打马赛克,删了

**Comment by maech01** [comment]
> 图片手机号没打马赛克,删了
已经打马赛克了

**Comment by maech01** [comment]
> > 图片手机号没打马赛克,删了
> > 已经打马赛克了

![Screenshot_20230309_135338_com termux_edit_261892862411599](https://user-images.githubusercontent.com/70949690/223933649-fd31cc04-b0d4-4a55-9243-42e7c13a8152.jpg)

**Comment by insoxin** [comment]
> > > 图片手机号没打马赛克,删了
> > > 已经打马赛克了
> 
> ![Screenshot_20230309_135338_com termux_edit_261892862411599](https://user-images.githubusercontent.com/70949690/223933649-fd31cc04-b0d4-4a55-9243-42e7c13a8152.jpg)

默认的配置无法运行,不用尝试其他的了,这个提示没有排错方向,相同的配置我可以运行,,, 

你有电脑吗？电视试试


这是ai的回答:

在 amd 架构上可以运行而在 Linux arm 上不行，可能是因为不同架构的处理器在处理数据时的方式不同，导致在 arm 架构上出现了这个问题。

**Comment by maech01** [comment]
> > > > 图片手机号没打马赛克,删了
> > > > 已经打马赛克了
> > 
> > 
> > ![Screenshot_20230309_135338_com termux_edit_261892862411599](https://user-images.githubusercontent.com/70949690/223933649-fd31cc04-b0d4-4a55-9243-42e7c13a8152.jpg)
> 
> 默认的配置无法运行,不用尝试其他的了,这个提示没有排错方向,相同的配置我可以运行,,,
> 
> 你有电脑吗？电视试试
> 
> 这是ai的回答:
> 
> 在 amd 架构上可以运行而在 Linux arm 上不行，可能是因为不同架构的处理器在处理数据时的方式不同，导致在 arm 架构上出现了这个问题。

电脑有但是没跑过脚本，我摸索一下

**Comment by maech01** [comment]
> > > > > 图片手机号没打马赛克,删了
> > > > > 已经打马赛克了
> > > 
> > > 
> > > ![Screenshot_20230309_135338_com termux_edit_261892862411599](https://user-images.githubusercontent.com/70949690/223933649-fd31cc04-b0d4-4a55-9243-42e7c13a8152.jpg)
> > 
> > 
> > 默认的配置无法运行,不用尝试其他的了,这个提示没有排错方向,相同的配置我可以运行,,,
> > 你有电脑吗？电视试试
> > 这是ai的回答:
> > 在 amd 架构上可以运行而在 Linux arm 上不行，可能是因为不同架构的处理器在处理数据时的方式不同，导致在 arm 架构上出现了这个问题。
> 
> 电脑有但是没跑过脚本，我摸索一下

用docker跑吗

**Comment by insoxin** [comment]
> > > > > > 图片手机号没打马赛克,删了
> > > > > > 已经打马赛克了
> > > > 
> > > > 
> > > > ![Screenshot_20230309_135338_com termux_edit_261892862411599](https://user-images.githubusercontent.com/70949690/223933649-fd31cc04-b0d4-4a55-9243-42e7c13a8152.jpg)
> > > 
> > > 
> > > 默认的配置无法运行,不用尝试其他的了,这个提示没有排错方向,相同的配置我可以运行,,,
> > > 你有电脑吗？电视试试
> > > 这是ai的回答:
> > > 在 amd 架构上可以运行而在 Linux arm 上不行，可能是因为不同架构的处理器在处理数据时的方式不同，导致在 arm 架构上出现了这个问题。
> > 
> > 
> > 电脑有但是没跑过脚本，我摸索一下
> 
> 用docker跑吗

不是,有windows版本,你看下列表,直接解压运行

**Comment by maech01** [comment]
> > > > > > > 图片手机号没打马赛克,删了
> > > > > > > 已经打马赛克了
> > > > > 
> > > > > 
> > > > > ![Screenshot_20230309_135338_com termux_edit_261892862411599](https://user-images.githubusercontent.com/70949690/223933649-fd31cc04-b0d4-4a55-9243-42e7c13a8152.jpg)
> > > > 
> > > > 
> > > > 默认的配置无法运行,不用尝试其他的了,这个提示没有排错方向,相同的配置我可以运行,,,
> > > > 你有电脑吗？电视试试
> > > > 这是ai的回答:
> > > > 在 amd 架构上可以运行而在 Linux arm 上不行，可能是因为不同架构的处理器在处理数据时的方式不同，导致在 arm 架构上出现了这个问题。
> > > 
> > > 
> > > 电脑有但是没跑过脚本，我摸索一下
> > 
> > 
> > 用docker跑吗
> 
> 不是,有windows版本,你看下列表,直接解压运行

好的

**Comment by maech01** [comment]
> > > > > > > > 图片手机号没打马赛克,删了
> > > > > > > > 已经打马赛克了
> > > > > > 
> > > > > > 
> > > > > > ![Screenshot_20230309_135338_com termux_edit_261892862411599](https://user-images.githubusercontent.com/70949690/223933649-fd31cc04-b0d4-4a55-9243-42e7c13a8152.jpg)
> > > > > 
> > > > > 
> > > > > 默认的配置无法运行,不用尝试其他的了,这个提示没有排错方向,相同的配置我可以运行,,,
> > > > > 你有电脑吗？电视试试
> > > > > 这是ai的回答:
> > > > > 在 amd 架构上可以运行而在 Linux arm 上不行，可能是因为不同架构的处理器在处理数据时的方式不同，导致在 arm 架构上出现了这个问题。
> > > > 
> > > > 
> > > > 电脑有但是没跑过脚本，我摸索一下
> > > 
> > > 
> > > 用docker跑吗
> > 
> > 
> > 不是,有windows版本,你看下列表,直接解压运行
> 
> 好的

![Uploading IMG_20230309_142357.jpg…]()

**Comment by maech01** [comment]
![Uploading IMG_20230309_142357.jpg…]()

**Comment by maech01** [comment]
电脑adm64提示出错自动关闭窗口

**Comment by insoxin** [comment]
> 电脑adm64提示出错自动关闭窗口

你发的图片看不到,

**Comment by maech01** [comment]
> > 电脑adm64提示出错自动关闭窗口
> 
> 你发的图片看不到,

![Uploading IMG_20230309_142357_edit_263704227404031.jpg…]()

**Comment by insoxin** [comment]
你自己能看到???要不直接复制错误信息？

**Comment by maech01** [comment]
![Uploading IMG_20230309_142357_edit_263704227404031-01.jpeg…]()

**Comment by maech01** [comment]
> 你自己能看到???要不直接复制错误信息？

复制不出来

**Comment by maech01** [comment]
中国电信助手 v1.0.9 For:https://t.me/ChinaTelecomHelper


免费使用,禁止买卖,仅限用于学习和研究目的；不得用于商业或者非法用途，否则，一切后果请用户自负。您必须在下载后的24个小时之内，从您的电脑中彻底删除。


正在解析配置文件

Users: 1

配置已完成解析

未开启授权自动化
开始请求电信客户端
出错了,请检查手机号和sign值后重试或更新到最新版本.

**Comment by maech01** [comment]
> 中国电信助手 v1.0.9 For:https://t.me/ChinaTelecomHelper
> 
> 免费使用,禁止买卖,仅限用于学习和研究目的；不得用于商业或者非法用途，否则，一切后果请用户自负。您必须在下载后的24个小时之内，从您的电脑中彻底删除。
> 
> 正在解析配置文件
> 
> Users: 1
> 
> 配置已完成解析
> 
> 未开启授权自动化 开始请求电信客户端 出错了,请检查手机号和sign值后重试或更新到最新版本.

win11的电脑

**Comment by insoxin** [comment]
> > 中国电信助手 v1.0.9 For:https://t.me/ChinaTelecomHelper
> > 免费使用,禁止买卖,仅限用于学习和研究目的；不得用于商业或者非法用途，否则，一切后果请用户自负。您必须在下载后的24个小时之内，从您的电脑中彻底删除。
> > 正在解析配置文件
> > Users: 1
> > 配置已完成解析
> > 未开启授权自动化 开始请求电信客户端 出错了,请检查手机号和sign值后重试或更新到最新版本.
> 
> win11的电脑

这样是对的,你没改配置文件吧,把手机号和sign填进去,

**Comment by maech01** [comment]
> > 中国电信助手 v1.0.9 For:https://t.me/ChinaTelecomHelper
> > 免费使用,禁止买卖,仅限用于学习和研究目的；不得用于商业或者非法用途，否则，一切后果请用户自负。您必须在下载后的24个小时之内，从您的电脑中彻底删除。
> > 正在解析配置文件
> > Users: 1
> > 配置已完成解析
> > 未开启授权自动化 开始请求电信客户端 出错了,请检查手机号和sign值后重试或更新到最新版本.
> 
> win11的电脑

Intel(R) Core(TM) i7-8750H CPU笔记本

**Comment by maech01** [comment]
> > > 中国电信助手 v1.0.9 For:https://t.me/ChinaTelecomHelper
> > > 免费使用,禁止买卖,仅限用于学习和研究目的；不得用于商业或者非法用途，否则，一切后果请用户自负。您必须在下载后的24个小时之内，从您的电脑中彻底删除。
> > > 正在解析配置文件
> > > Users: 1
> > > 配置已完成解析
> > > 未开启授权自动化 开始请求电信客户端 出错了,请检查手机号和sign值后重试或更新到最新版本.
> > 
> > 
> > win11的电脑
> 
> 这样是对的,你没改配置文件吧,把手机号和sign填进去,

可以了

中国电信助手 v1.0.9 For:https://t.me/ChinaTelecomHelper


免费使用,禁止买卖,仅限用于学习和研究目的；不得用于商业或者非法用途，否则，一切后果请用户自负。您必须在下载后的24个小时之内，从您的电脑中彻底删除。


正在解析配置文件

Users: 1

配置已完成解析

未开启授权自动化
开始请求电信客户端
更新User-Agent等值成功
重新序列化
重新写入config.json


最新版本:1.0.9更新时间:2023-03-08T15:53:09Z
未开启自动更新,自动跳过


开始获取北京时间:

话费兑换:
开始800金豆兑换5元话费(每月两次):未找到参数设置,自动跳过
开始400金豆兑换2元话费(每月两次):未找到参数设置,自动跳过
开始200金豆兑换1元话费(每月三次):未找到参数设置,自动跳过
开始200金豆兑换1元话费(每连签七天可兑换一次):未找到参数设置,自动跳过
开始200金豆兑换1元话费(每月三次):未找到参数设置,自动跳过


会员兑换:
开始240金豆兑换5元网易严选纯享季卡:未找到参数设置,自动跳过
开始1000金豆兑换优酷视频会员月卡:未找到参数设置,自动跳过
开始600金豆兑换腾讯视频会员周卡:未找到参数设置,自动跳过
开始300金豆兑换芒果tv会员周卡:未找到参数设置,自动跳过
开始500金豆兑换爱音乐会员月卡:未找到参数设置,自动跳过


开始喂食任务
开始第1次喂食:
开始第2次喂食:
开始第3次喂食:
开始第4次喂食:
开始第5次喂食:
开始第6次喂食:
开始第7次喂食:
开始第8次喂食:
开始第9次喂食:
开始第10次喂食:


金豆任务
登录任务+5金豆
查看权益中心+5金豆
查看我的云盘+10金豆
打开消息+100金豆
当日分享+50金豆
访问宽带余额+15金豆
访问我的宽带+15金豆
查看装修进度+15金豆
查看我的金豆+5金豆
观看直播15s+5金豆:参数解析错误
查看我的订单+5金豆
查看视频彩铃+10金豆

**Comment by maech01** [comment]
> > > > 中国电信助手 v1.0.9 For:https://t.me/ChinaTelecomHelper
> > > > 免费使用,禁止买卖,仅限用于学习和研究目的；不得用于商业或者非法用途，否则，一切后果请用户自负。您必须在下载后的24个小时之内，从您的电脑中彻底删除。
> > > > 正在解析配置文件
> > > > Users: 1
> > > > 配置已完成解析
> > > > 未开启授权自动化 开始请求电信客户端 出错了,请检查手机号和sign值后重试或更新到最新版本.
> > > 
> > > 
> > > win11的电脑
> > 
> > 
> > 这样是对的,你没改配置文件吧,把手机号和sign填进去,
> 
> 可以了
> 
> 中国电信助手 v1.0.9 For:https://t.me/ChinaTelecomHelper
> 
> 免费使用,禁止买卖,仅限用于学习和研究目的；不得用于商业或者非法用途，否则，一切后果请用户自负。您必须在下载后的24个小时之内，从您的电脑中彻底删除。
> 
> 正在解析配置文件
> 
> Users: 1
> 
> 配置已完成解析
> 
> 未开启授权自动化 开始请求电信客户端 更新User-Agent等值成功 重新序列化 重新写入config.json
> 
> 最新版本:1.0.9更新时间:2023-03-08T15:53:09Z 未开启自动更新,自动跳过
> 
> 开始获取北京时间:
> 
> 话费兑换: 开始800金豆兑换5元话费(每月两次):未找到参数设置,自动跳过 开始400金豆兑换2元话费(每月两次):未找到参数设置,自动跳过 开始200金豆兑换1元话费(每月三次):未找到参数设置,自动跳过 开始200金豆兑换1元话费(每连签七天可兑换一次):未找到参数设置,自动跳过 开始200金豆兑换1元话费(每月三次):未找到参数设置,自动跳过
> 
> 会员兑换: 开始240金豆兑换5元网易严选纯享季卡:未找到参数设置,自动跳过 开始1000金豆兑换优酷视频会员月卡:未找到参数设置,自动跳过 开始600金豆兑换腾讯视频会员周卡:未找到参数设置,自动跳过 开始300金豆兑换芒果tv会员周卡:未找到参数设置,自动跳过 开始500金豆兑换爱音乐会员月卡:未找到参数设置,自动跳过
> 
> 开始喂食任务 开始第1次喂食: 开始第2次喂食: 开始第3次喂食: 开始第4次喂食: 开始第5次喂食: 开始第6次喂食: 开始第7次喂食: 开始第8次喂食: 开始第9次喂食: 开始第10次喂食:
> 
> 金豆任务 登录任务+5金豆 查看权益中心+5金豆 查看我的云盘+10金豆 打开消息+100金豆 当日分享+50金豆 访问宽带余额+15金豆 访问我的宽带+15金豆 查看装修进度+15金豆 查看我的金豆+5金豆 观看直播15s+5金豆:参数解析错误 查看我的订单+5金豆 查看视频彩铃+10金豆

但是电脑不常用啊，手机修不了了吗？

**Comment by maech01** [comment]
> 主要是手机不知道怎么修,,你看相同的配置,电脑可以,手机不行,,,

我看了1.07住文件没改过是不是rsa文件夹用go语言不可以识别

**Comment by maech01** [comment]
> > 主要是手机不知道怎么修,,你看相同的配置,电脑可以,手机不行,,,
> 
> 我看了1.07住文件没改过是不是rsa文件夹用go语言不可以识别

用1.09电脑跑过，再用1.09的数据跑1.07可以吗？

**Comment by insoxin** [comment]
> > > 主要是手机不知道怎么修,,你看相同的配置,电脑可以,手机不行,,,
> > 
> > 
> > 我看了1.07住文件没改过是不是rsa文件夹用go语言不可以识别
> 
> 用1.09电脑跑过，再用1.09的数据跑1.07可以吗？

这个不行的唉.那个sign参数,最近几星期,电信才增加的.旧版本不支持.主要是这个报错,没有头绪,我问问其他的大佬怎么搞吧

**Comment by maech01** [comment]
多账号怎么用？再复制{}里面数据另起一行吗？

**Comment by insoxin** [comment]
你这个解决了,大佬说你这个是32 位 arch ,大概晚上或明天我有空更新一下
多账号新建个配置文件,有人收费代挂,去掉了

**Comment by maech01** [comment]
> 你这个解决了,大佬说你这个是32 位 arch ,大概晚上或明天我有空更新一下 多账号新建个配置文件,有人收费代挂,去掉了

大佬辛苦

**Comment by maech01** [comment]
中国电信助手 v1.0.10 For:https://t.me/ChinaTelecomHelper


免费使用,禁止买卖,仅限用于学习和研究目的；不得用于商业或者非法用途，否则，一切后果请用户自负。您必须在下载后的24个小时之内，从您的电脑中彻底删除。


正在解析配置文件

Users: 1

配置已完成解析

未开启授权自动化
Unmarshal response failed:  invalid character '<' looking for beginning of value
root@localhost:~/Telecom $ ./China-Telecom-Helper_linux_arm

中国电信助手 v1.0.10 For:https://t.me/ChinaTelecomHelper


免费使用,禁止买卖,仅限用于学习和研究目的；不得用于商业或者非法用途，否则，一切后果请用户自负。您必须在下载后的24个小时之内，从您的电脑中彻底删除。


正在解析配置文件

Users: 1

配置已完成解析

未开启授权自动化
Unmarshal response failed:  invalid character '<' looking for beginning of value
root@localhost:~/Telecom $

提示一个无效字符<

**Comment by insoxin** [comment]
我去加个日志时间,另外不应该啊,你电脑再试下,看可以不,还是这个版本问题.

**Comment by maech01** [comment]
> 我去加个日志时间,另外不应该啊,你电脑再试下,看可以不,还是这个版本问题.

配置文件和电脑一样，电脑正常运行，手机提示<符号

**Comment by maech01** [comment]
> > 我去加个日志时间,另外不应该啊,你电脑再试下,看可以不,还是这个版本问题.
> 
> 配置文件和电脑一样，电脑正常运行，手机提示<符号

手机文件可以运行了，但是运行后配置文件数据没有自动写入

**Comment by insoxin** [comment]
> > > > > 我去加个日志时间,另外不应该啊,你电脑再试下,看可以不,还是这个版本问题.
> > > > 
> > > > 
> > > > 配置文件和电脑一样，电脑正常运行，手机提示<符号
> > > 
> > > 
> > > 手机文件可以运行了，但是运行后配置文件数据没有自动写入
> > 
> > 
> > 中国电信助手 v1.0.10 For:https://t.me/ChinaTelecomHelper
> > 免费使用,禁止买卖,仅限用于学习和研究目的；不得用于商业或者非法用途，否则，一切后果请用户自负。您必须在下载后的24个小时之内，从您的电脑中彻底删除。
> > 正在解析配置文件
> > Users: 1
> > 配置已完成解析
> > 未开启授权自动化 开始请求电信客户端 出错了,请检查手机号和sign值后重试或更新到最新版本. 我把电脑登陆后的配置文件复制进去还是不可以
> 
> sign值是不是有效期很短，就过期了？电脑也出错了，原来手机连机场出现<符号错误，关掉机场就没出现<符号了

对,这个问题其他有讨论,这个issues太长了,我删了
