### ISSUE TITLE
一直提示未开启授权自动化，手动填参数没用

### ISSUE THREAD

**Issue by mmxzwj** [insoxin/China-Telecom-Helper#105]
一直提示未开启授权自动化，手动填参数没用

![image](https://user-images.githubusercontent.com/101969595/223917633-6d35db39-9af2-45b2-9cc7-e8c7a515f9ef.png)

**Comment by insoxin** [comment]
配置文件贴出来,打码别忘了

**Comment by mmxzwj** [comment]
> 配置文件贴出来，打码别忘记了
![image](https://user-images.githubusercontent.com/101969595/223918338-05203395-ae0c-4a89-8aff-5c6b3fdeb9c0.png)

**Comment by mmxzwj** [comment]
看看哪里有问题，

**Comment by insoxin** [comment]
你运行页面的截图

**Comment by mmxzwj** [comment]
> 你运行页面的截图
可以运行了。
