### ISSUE TITLE
手机又出错了

### ISSUE THREAD

**Issue by maech01** [insoxin/China-Telecom-Helper#107]
正在解析配置文件

Users: 1

配置已完成解析

未开启授权自动化
Unmarshal response failed: unexpected end of JSON input

最新版1.0.10不可以运行了，刚开始那个1.0.10版本还可以运行，就是sign过期快

**Comment by insoxin** [comment]
我加了日志时间你这里没显示

**Comment by ww176883** [comment]
我1.0.9也报这个问题Unmarshal response failed: unexpected end of JSON input, 我在本机能正常运行,放服务器就不行了

**Comment by insoxin** [comment]
> 我1.0.9也报这个问题Unmarshal response failed: unexpected end of JSON input, 我在本机能正常运行,放服务器就不行了

我加了这个日志时间,你那里没显示吗

**Comment by insoxin** [comment]
你们两个人都没显示,我怀疑我上传错版本了😥

**Comment by ww176883** [comment]
> > 我1.0.9也报这个问题Unmarshal response failed: unexpected end of JSON input, 我在本机能正常运行,放服务器就不行了
> 
> 我加了这个日志时间,你那里没显示吗

![image](https://user-images.githubusercontent.com/38782298/224199903-489ce382-a3ef-4f69-ab59-e52f66825235.png)
没有显示

**Comment by ww176883** [comment]
windows版本的正常打印时间了,正常运行
![image](https://user-images.githubusercontent.com/38782298/224200504-5be2a2c3-b623-4333-ab98-a0dbd8dca11e.png)
linux版本的运行不了,一样的配置
![image](https://user-images.githubusercontent.com/38782298/224200573-d42f85ff-4edc-4ba1-8238-9af5a5f0d09b.png)

**Comment by insoxin** [comment]
那应该我传错测试版本了,,已经定位到原因,我稍后重传一下

**Comment by insoxin** [comment]
昨天给群友编译了好几个版本,估计搞混了,非常抱歉

**Comment by insoxin** [comment]
@ww176883 @maech01 让朋友传上了新版本, 试下看看,

**Comment by maech01** [comment]
> @ww176883 @maech01 让朋友传上了新版本, 试下看看,

好的

**Comment by ww176883** [comment]
好的

**Comment by ww176883** [comment]
sign失效很快是不是每天都得抓,只能用短信登录吗,但是短信登录又一直显示重新发送

**Comment by insoxin** [comment]
> sign失效很快是不是每天都得抓,只能用短信登录吗,但是短信登录又一直显示重新发送

对很快,我之前抓了半个月...才稳定下来.稳定原因未知.也许是认设备?

有密码登录版本,没放出来,,主要是涉及这个安全,去年被人黑过~~~

这个sign参数推出应该没两个月吧,还在探索中.

**Comment by ww176883** [comment]
> > sign失效很快是不是每天都得抓,只能用短信登录吗,但是短信登录又一直显示重新发送
> 
> 对很快,我之前抓了半个月...才稳定下来.稳定原因未知.也许是认设备?
> 
> 有密码登录版本,没放出来,,主要是涉及这个安全,去年被人黑过~~~
> 
> 这个sign参数推出应该没两个月吧,还在探索中.

好吧,感谢大佬的无私奉献

**Comment by maech01** [comment]
> > @ww176883 @maech01 让朋友传上了新版本, 试下看看,
> 
> 好的

正在解析配置文件

Users: 1

配置已完成解析

未开启授权自动化
2023/03/10 10:35:12 开始请求电信客户端
2023/03/10 10:35:12 出错了,请检查手机号和sign值是否有效后重试或更新到最新版本

还是不可以，可以加入ua自己修改吗？

**Comment by insoxin** [comment]
> > > @ww176883 @maech01 让朋友传上了新版本, 试下看看,
> > 
> > 
> > 好的
> 
> 正在解析配置文件
> 
> Users: 1
> 
> 配置已完成解析
> 
> 未开启授权自动化 2023/03/10 10:35:12 开始请求电信客户端 2023/03/10 10:35:12 出错了,请检查手机号和sign值是否有效后重试或更新到最新版本
> 
> 还是不可以，可以加入ua自己修改吗？

重新抓虾sign值

**Comment by maech01** [comment]
> > > > @ww176883 @maech01 让朋友传上了新版本, 试下看看,
> > > 
> > > 
> > > 好的
> > 
> > 
> > 正在解析配置文件
> > Users: 1
> > 配置已完成解析
> > 未开启授权自动化 2023/03/10 10:35:12 开始请求电信客户端 2023/03/10 10:35:12 出错了,请检查手机号和sign值是否有效后重试或更新到最新版本
> > 还是不可以，可以加入ua自己修改吗？
> 
> 重新抓虾sign值,,,ua自己修改这个就是群友让我去掉自定义,很多人不会抓包,头大....

可以了，刚刚把sign复制错了😂

**Comment by maech01** [comment]
> > > > > @ww176883 @maech01 让朋友传上了新版本, 试下看看,
> > > > 
> > > > 
> > > > 好的
> > > 
> > > 
> > > 正在解析配置文件
> > > Users: 1
> > > 配置已完成解析
> > > 未开启授权自动化 2023/03/10 10:35:12 开始请求电信客户端 2023/03/10 10:35:12 出错了,请检查手机号和sign值是否有效后重试或更新到最新版本
> > > 还是不可以，可以加入ua自己修改吗？
> > 
> > 
> > 重新抓虾sign值,,,ua自己修改这个就是群友让我去掉自定义,很多人不会抓包,头大....
> 
> 可以了，刚刚把sign复制错了😂

问题是没有ios设备，会不会是检测设备所以sign值过期快

**Comment by insoxin** [comment]
> > > > > > @ww176883 @maech01 让朋友传上了新版本, 试下看看,
> > > > > 
> > > > > 
> > > > > 好的
> > > > 
> > > > 
> > > > 正在解析配置文件
> > > > Users: 1
> > > > 配置已完成解析
> > > > 未开启授权自动化 2023/03/10 10:35:12 开始请求电信客户端 2023/03/10 10:35:12 出错了,请检查手机号和sign值是否有效后重试或更新到最新版本
> > > > 还是不可以，可以加入ua自己修改吗？
> > > 
> > > 
> > > 重新抓虾sign值,,,ua自己修改这个就是群友让我去掉自定义,很多人不会抓包,头大....
> > 
> > 
> > 可以了，刚刚把sign复制错了😂
> 
> 问题是没有ios设备，会不会是检测设备所以sign值过期快

也许是,无法确定,还在探索中
