### ISSUE TITLE
https://api.isoyu.com/10000/user/send/获取的sign码

### ISSUE THREAD

**Issue by chenv12** [insoxin/China-Telecom-Helper#109]
中国电信助手 v1.0.11 For:https://t.me/ChinaTelecomHelper

免费使用,禁止买卖,仅限用于学习和研究目的；不得用于商业或者非法用途，否则，一切后果请用户自负。您必须在下载后的24个小时之内，从您的电脑中彻底删除。

正在解析配置文件

Users: 1

配置已完成解析

未开启授权自动化
2023/03/10 14:15:10 开始请求电信客户端
2023/03/10 14:15:10 出错了,请检查手机号和sign值是否有效后重试或更新到最新版本.

**Comment by chenv12** [comment]
手机号，sign码输入都是真确的
{
	"users": [{
		"AutoUpdate": "false",
		"systime": "http://cloudflare.api.isoyu.com/time/SysTime/?appCode=B586A14C4EC466D33682F8626CCB3794&auturl=api.isoyu.com&num=13",
		"Authorization": "false",
		"alipay": "",
		"sign": "490c2aa709ebec499f2cdedb4ab7f3xx",
		"ua": "",
		"Monthlybeans": "",
		"cookie": "cookie",
		"Notice": "https://t.me/ChinaTelecomHelper",
		"phone": 166027299xx,
		"para": [{
			"setting": "true"
		}, {
			"para156": ""
		}, {
			"para256": ""
		}, {
			"para768": ""
		}],
		"Paradise": [{
			"Polymerize": ""
		}, {
			"Polymerize": ""
		}, {
			"Polymerize": ""
		}]
	}]
}

**Comment by insoxin** [comment]
![image](https://user-images.githubusercontent.com/19371836/224239346-5ba802fc-e920-4ef0-890b-712096c3d66e.png)
这个加黑加粗要看的啊

**Comment by chenv12** [comment]
Centos7如何安装China-Telecom-Helper？下载[China-Telecom-Helper_linux_386.tar.gz]这个版本吗？求教程。

**Comment by insoxin** [comment]
> Centos7如何安装China-Telecom-Helper？下载[China-Telecom-Helper_linux_386.tar.gz]这个版本吗？求教程。

不是安装直接运行

**Comment by chenv12** [comment]
菜鸟表示不会 。我是PVE上安装的Centos7，可以教我大概的操作流程？万分感激。

**Comment by chenv12** [comment]
![1](https://user-images.githubusercontent.com/34930155/224244849-949326b0-355d-4e99-a556-521abe61f699.png)
![2](https://user-images.githubusercontent.com/34930155/224244981-47234ab3-e486-4fdf-882e-5594b444f6cb.png)

**Comment by insoxin** [comment]
大概这两天有空我再更新下相关教程吧

**Comment by insoxin** [comment]
> 菜鸟表示不会 。我是PVE上安装的Centos7，可以教我大概的操作流程？万分感激。

https://github.com/insoxin/China-Telecom-Helper#以linux系统-电信助手版本1011为例
