### ISSUE TITLE
sing登录不上

### ISSUE THREAD

**Issue by shen115** [insoxin/China-Telecom-Helper#111]
免费使用,禁止买卖,仅限用于学习和研究目的；不得用于商业或者非法用途，否则，一切后果请用户自负。您必须在下载后的24个小时之内，从您的电脑中彻底删除。

正在解析配置文件

Users: 1

配置已完成解析

未开启授权自动化
2023/03/10 15:24:23 开始请求电信客户端
2023/03/10 15:24:23 出错了,请检查手机号和sign值是否有效后重试或更新到最新版本.

**Comment by chenpinetree** [comment]
我也是一直遇到这个问题，重新抓，而且sign好像很快就会过期，不知道是时间还是次数。至少我试着跑第三次的时候已经出现这个问题了。10分钟内

**Comment by chm512512** [comment]
我压根抓到这个值。截个图看看到底是啥？

**Comment by chm512512** [comment]
> 我也是一直遇到这个问题，重新抓，而且sign好像很快就会过期，不知道是时间还是次数。至少我试着跑第三次的时候已经出现这个问题了。10分钟内

大哥 截个图看看

**Comment by chenpinetree** [comment]
> 我压根抓到这个值。截个图看看到底是啥？

作者的guild要不就是写错了，要不就是每个地区登入界面不一样。应该是电信app-我的-左上角-点击那个金豆专属礼 （点击前就应该要开启抓包）

<img width="476" alt="iShot_2023-03-10_18 03 31" src="https://user-images.githubusercontent.com/43738241/224287416-37eee841-2c6d-41ff-8268-ab381831f84f.png">

出现这个页面后就可以停止抓包了

<img width="471" alt="iShot_2023-03-10_18 04 19" src="https://user-images.githubusercontent.com/43738241/224287890-52c33845-ae92-485b-81ca-9329a16b5da1.png">

抓包软件那里过滤出wapside.189.cn的结果，然后一个个进去看，会找到sign的值！

这个够傻瓜了够详细了，作者没有写详细。

**Comment by chm512512** [comment]
> 

湖北，最新版app，项目名都加密了。第一次用，不知道那个是的。paradise 抓了一大把。一个sign没看到🤣

**Comment by mmkakac** [comment]
> 

老哥，最后再具体点，抓包软件里面sign在哪里能截个图吗

**Comment by mmkakac** [comment]
> > 我压根抓到这个值。截个图看看到底是啥？
> 
> 作者的指南要不就是写错了，要不就是每个地区登入界面不一样。应该是电信app-我的-左上角-点击那个金豆专属礼 （点击前就应该要开启抓包）
> 
> <img alt="iShot_2023-03-10_18 03 31" width="476" src="https://user-images.githubusercontent.com/43738241/224287416-37eee841-2c6d-41ff-8268-ab381831f84f.png">
> 
> 出现这个页面后就可以停止抓包了
> 
> <img alt="iShot_2023-03-10_18 04 19" width="471" src="https://user-images.githubusercontent.com/43738241/224287890-52c33845-ae92-485b-81ca-9329a16b5da1.png">
> 
> 抓包软件那里过滤出wapside.189.cn的结果，然后一个个进去看，会找到sign的值！
> 
> 这个够傻瓜了够详细了，作者没有写详细。

老哥，最后再具体点，抓包软件里面sign在哪里能截个图吗

**Comment by shen115** [comment]
手机未root黄鸟抓包进不去后面这个界面

**Comment by chenpinetree** [comment]
> > > 我压根抓到这个值。截个图看看到底是啥？
> > 
> > 
> > 作者的指南要不就是写错了，要不就是每个地区登入界面不一样。应该是电信app-我的-左上角-点击那个金豆专属礼 （点击前就应该要开启抓包）
> > <img alt="iShot_2023-03-10_18 03 31" width="476" src="https://user-images.githubusercontent.com/43738241/224287416-37eee841-2c6d-41ff-8268-ab381831f84f.png">
> > 出现这个页面后就可以停止抓包了
> > <img alt="iShot_2023-03-10_18 04 19" width="471" src="https://user-images.githubusercontent.com/43738241/224287890-52c33845-ae92-485b-81ca-9329a16b5da1.png">
> > 抓包软件那里过滤出wapside.189.cn的结果，然后一个个进去看，会找到sign的值！
> > 这个够傻瓜了够详细了，作者没有写详细。
> 
> 老哥，最后再具体点，抓包软件里面sign在哪里能截个图吗

没办法~每个软件显示的都不一样啊，单单我自己就用3个不同的抓包软件，每个的显示界面都稍微不同，你就一个个点进去看

**Comment by chenpinetree** [comment]
> 手机未root黄鸟抓包进不去后面这个界面

不用root吧，我的安卓手机没有root也正常使用

**Comment by insoxin** [comment]
> > 我压根抓到这个值。截个图看看到底是啥？
> 
> 作者的指南要不就是写错了，要不就是每个地区登入界面不一样。应该是电信app-我的-左上角-点击那个金豆专属礼 （点击前就应该要开启抓包）
> 
> <img alt="iShot_2023-03-10_18 03 31" width="476" src="https://user-images.githubusercontent.com/43738241/224287416-37eee841-2c6d-41ff-8268-ab381831f84f.png">
> 
> 出现这个页面后就可以停止抓包了
> 
> <img alt="iShot_2023-03-10_18 04 19" width="471" src="https://user-images.githubusercontent.com/43738241/224287890-52c33845-ae92-485b-81ca-9329a16b5da1.png">
> 
> 抓包软件那里过滤出wapside.189.cn的结果，然后一个个进去看，会找到sign的值！
> 
> 这个够傻瓜了够详细了，作者没有写详细。

我那个抓包教程一年前写的,,.你这个图我可以放在教程里吗？

**Comment by insoxin** [comment]
> 

请求头找到cookie 然后下拉

**Comment by insoxin** [comment]
> 湖北，最新版app，项目名都加密了。第一次用，不知道那个是的。paradise 抓了一大把。一个sign没看到🤣

请求头找到cookie 然后下拉

**Comment by insoxin** [comment]
https://github.com/insoxin/China-Telecom-Helper/wiki/一些数据值的抓包教程


更新了教程

**Comment by chm512512** [comment]
> [https://github.com/insoxin/China-Telecom-Helper/wiki/一些数据值的抓包教程](https://github.com/insoxin/China-Telecom-Helper/wiki/%E4%B8%80%E4%BA%9B%E6%95%B0%E6%8D%AE%E5%80%BC%E7%9A%84%E6%8A%93%E5%8C%85%E6%95%99%E7%A8%8B)
> 
> 更新了教程

好的 找到了。之前没仔细看🤣大佬用心他

**Comment by chm512512** [comment]
> 

httpcancry的位置 在ua的下面

**Comment by shen115** [comment]
![4e2e8b35c13154e62c383514c972465](https://user-images.githubusercontent.com/48236779/224315309-5ced98bd-0a95-47c2-86ca-f7367712e3c6.jpg)
开启抓包就一直卡在这里进不去

**Comment by insoxin** [comment]
> ![4e2e8b35c13154e62c383514c972465](https://user-images.githubusercontent.com/48236779/224315309-5ced98bd-0a95-47c2-86ca-f7367712e3c6.jpg)
> 开启抓包就一直卡在这里进不去

进去后再开启抓包试试

**Comment by shen115** [comment]
![image](https://user-images.githubusercontent.com/48236779/224317941-0d893bef-1b7b-4e33-bf5f-4b45e9c303cf.png)
抓到了，软件运行一直提醒网络异常

**Comment by insoxin** [comment]
@shen115 你用的是最新版吗？

**Comment by shen115** [comment]
中国电信助手 v1.0.11 For:https://t.me/ChinaTelecomHelper
应该是最新的

**Comment by insoxin** [comment]
> 中国电信助手 v1.0.11 For:https://t.me/ChinaTelecomHelper
> 应该是最新的

具体时间有吗,

**Comment by shen115** [comment]
啥意思，版本是今天下午才下载的最新的，我重新安装一遍试试

**Comment by insoxin** [comment]
> 啥意思，版本是今天下午才下载的最新的，我重新安装一遍试试

不用下,你刚刚执行的具体时间有吗？我查下日志

**Comment by shen115** [comment]
有22:55我又执行了一遍，你看看日志1890390****

**Comment by chenpinetree** [comment]
> 

可以~

**Comment by chenpinetree** [comment]
> > > 我压根抓到这个值。截个图看看到底是啥？
> > 
> > 
> > 作者的指南要不就是写错了，要不就是每个地区登入界面不一样。应该是电信app-我的-左上角-点击那个金豆专属礼 （点击前就应该要开启抓包）
> > <img alt="iShot_2023-03-10_18 03 31" width="476" src="https://user-images.githubusercontent.com/43738241/224287416-37eee841-2c6d-41ff-8268-ab381831f84f.png">
> > 出现这个页面后就可以停止抓包了
> > <img alt="iShot_2023-03-10_18 04 19" width="471" src="https://user-images.githubusercontent.com/43738241/224287890-52c33845-ae92-485b-81ca-9329a16b5da1.png">
> > 抓包软件那里过滤出wapside.189.cn的结果，然后一个个进去看，会找到sign的值！
> > 这个够傻瓜了够详细了，作者没有写详细。
> 
> 我那个抓包教程一年前写的,,.你这个图我可以放在教程里吗？

可以

**Comment by insoxin** [comment]
> 有22:55我又执行了一遍，你看看日志1890390****

我们时区不同吗？

**Comment by insoxin** [comment]
> 有22:55我又执行了一遍，你看看日志1890390****

http://cloudflare.api.isoyu.com/time/SysTime/?appCode=B586A14C4EC466D33682F8626CCB3794&auturl=api.isoyu.com&num=13

这个你应该也访问不了吧???

**Comment by insoxin** [comment]
> 有22:55我又执行了一遍，你看看日志1890390****

你地区网络墙了cloudflare,用1.0.12版本,换了国内的cdn

**Comment by shen115** [comment]
我试试

**Comment by shen115** [comment]
可以登录上，执行第一次提醒：2023/03/10 22:45:08 开始请求电信客户端
2023/03/10 22:45:08 更新User-Agent等值成功
2023/03/10 22:45:08 重新序列化
2023/03/10 22:45:08 重新写入config.json
最新版本:1.0.12更新时间:2023-03-10T11:59:05Z
可以正常做任务。
但是手动执行第二遍就又提示出错了,请检查手机号和sign值是否有效后重试或更新到最新版本.

**Comment by insoxin** [comment]
> 可以登录上，执行第一次提醒：2023/03/10 22:45:08 开始请求电信客户端
> 2023/03/10 22:45:08 更新User-Agent等值成功
> 2023/03/10 22:45:08 重新序列化
> 2023/03/10 22:45:08 重新写入config.json
> 最新版本:1.0.12更新时间:2023-03-10T11:59:05Z
> 可以正常做任务。
> 但是手动执行第二遍就又提示出错了,请检查手机号和sign值是否有效后重试或更新到最新版本.

这个有的人说sign有效期是一天,有的说二十分钟,还有的说是十分钟,你反馈貌似在一分钟以内,,,,每个人都不同吗

**Comment by shen115** [comment]
我看你获取到了cookie也不行？如果sign是短期那就很恶心了

**Comment by insoxin** [comment]
> 我看你获取到了cookie也不行？如果sign是短期那就很恶心了

我的持续应该快一星期了,还能用,,还在探索中
