### ISSUE TITLE
网络错误问题

### ISSUE THREAD

**Issue by chm512512** [insoxin/China-Telecom-Helper#112]
**软件版本**
v1.0.11

**问题日志**
填写了sign和phone，运行一次直接提示网络错误，重试或升级新版。后面就是url+sign+phone，然后一个ip 返回 信息。人都麻了，再跑一次又失效了又要抓。

**使用环境**
arm设备，电信wifi，电信LTE均网络错误。

请问是我网络问题还是你的服务器问题，或者是电信服务器的问题

**Comment by chm512512** [comment]
systime 使用的cloudflare 好像打不开，等我换另一个试试

**Comment by chm512512** [comment]
> 
 确实，打不开。应该是拦截，人都抓麻了…跑一次就要抓一次…

**Comment by chm512512** [comment]
> > 确实，打不开。应该是拦截，人都抓麻了…跑一次就要抓一次…
> 
> 如果是这个问题,我更换下国内的cdn,你是泉州吗？泉州有白名单机制.

我是湖北的，明天再给你测试了。我要打个游戏放松一下！

**Comment by insoxin** [comment]
新版本,换了国内的cdn,
