### ISSUE TITLE
-ash: 0: command not found

### ISSUE THREAD

**Issue by chenv12** [insoxin/China-Telecom-Helper#114]
![1](https://user-images.githubusercontent.com/34930155/224472033-2c3267b2-e552-40b7-9913-acb89f3b1ad6.png)

**Comment by insoxin** [comment]
不要死板按示例,每个人下的目录地址都不一样

**Comment by insoxin** [comment]
你后面  执行时前面加个./

**Comment by chenv12** [comment]
![1](https://user-images.githubusercontent.com/34930155/224481476-d8f528e8-6021-4e88-ba14-d54137457e0a.png)
0 0,8,16 * * * cd /root/China-Telecom-Helper_linux_386/ && ./China-Telecom-Helper_linux_386
是不是需要装指令。5555

**Comment by chenv12** [comment]
[root@localhost ~]# 0 0,8,16 * * * cd /root/China-Telecom-Helper_linux_386/ && ./China-Telecom-Helper_linux_386
-bash: 0: 未找到命令

**Comment by insoxin** [comment]
我意思在这之前你先试运行一下./China-Telecom-Helper_linux_386

**Comment by chenv12** [comment]
0 0,8,16 * * * cd /root/China-Telecom-Helper_linux_386/ && ./China-Telecom-Helper_linux_386

**Comment by insoxin** [comment]
等下我看到你图片能成功运行

**Comment by chenv12** [comment]
[root@localhost China-Telecom-Helper_linux_386]# ./China-Telecom-Helper_linux_386

中国电信助手 v1.0.12 For:https://t.me/ChinaTelecomHelper


免费使用,禁止买卖,仅限用于学习和研究目的；不得用于商业或者非法用途，否则，一切后果请用户自负。您必须在下载后的24个小时之内，从您的电脑中彻底删除。


正在解析配置文件

Users: 1

配置已完成解析

未开启授权自动化
2023/03/11 19:37:48 开始请求电信客户端
2023/03/11 19:37:48 出错了,请检查手机号和sign值是否有效后重试或更新到最新版本.

**Comment by chenv12** [comment]
> 等下我看到你图片能成功运行

最后面的定时执行脚本无法加上去

**Comment by insoxin** [comment]
/etc/crontab


执行这个

**Comment by chenv12** [comment]
Last login: Sat Mar 11 19:32:05 2023 from 192.168.1.120
[root@localhost ~]# /etc/crontab
-bash: /etc/crontab: 权限不够

**Comment by insoxin** [comment]
crontab   这样呢？

**Comment by chenv12** [comment]
[root@localhost ~]# crontab

**Comment by chenv12** [comment]
[root@localhost ~]# crontab
接下来没有任何反应

**Comment by chenv12** [comment]
[root@localhost ~]# crontab
[root@localhost ~]# crontab

**Comment by insoxin** [comment]
这我知识盲区了,我搜搜

**Comment by chenv12** [comment]
辛苦了！！！！哈哈哈

**Comment by insoxin** [comment]
搜了下,大部分说是没有权限,但是我看你登录是root   

你试试sudo /etc/crontab


和 sudo 0 0,8,16 * * * cd /root/China-Telecom-Helper_linux_386/ && ./China-Telecom-Helper_linux_386

**Comment by chenv12** [comment]
[root@localhost ~]# sudo /etc/crontab
sudo: /etc/crontab：找不到命令

**Comment by chenv12** [comment]
[root@localhost ~]# sudo 0 0,8,16 * * * cd /root/China-Telecom-Helper_linux_386/ && ./China-Telecom-Helper_linux_386
sudo: 0：找不到命令

**Comment by insoxin** [comment]
顺便问下,你这是虚拟机吗？windows也可以使用这个软件的,只是拿Linux举的例子

**Comment by chenv12** [comment]
PVE虚拟机

**Comment by chenv12** [comment]
windows挂机不方便，PVE里面可以24小时挂机

**Comment by insoxin** [comment]
sudo crontab -e   再试试这个,,

**Comment by chenv12** [comment]
[root@localhost ~]# sudo crontab -e
* * * * * /root/cf-v4-ddns.sh >/dev/null 2>&1
* * * * * sleep 30 && /root/cf-v4-ddns.sh >/dev/null
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
"/tmp/crontab.TZSZMy" 2L, 99C

**Comment by insoxin** [comment]
在里面加上  0 0,8,16 * * * cd /root/China-Telecom-Helper_linux_386/ && ./China-Telecom-Helper_linux_386  这个文本

**Comment by chenv12** [comment]
* * * * * /root/cf-v4-ddns.sh >/dev/null 2>&1
* * * * * sleep 30 && /root/cf-v4-ddns.sh >/dev/null
0 0,8,16 * * * cd /root/China-Telecom-Helper_linux_386/ && ./China-Telecom-Helper_linux_386

**Comment by chenv12** [comment]
这样吗

**Comment by insoxin** [comment]
> 这样吗

无法确定,看着应该是,没用过你这个,,实践出真知

**Comment by insoxin** [comment]
其实说成本,你这个24小时一直开着虚拟机,真不如用windows定时任务启动挂,如果你还挂着其他项目当我没说

**Comment by chenv12** [comment]
添加进去了如何保存啊！不会保存，哈哈

**Comment by chenv12** [comment]
[root@localhost ~]# sudo crontab -e
* * * * * /root/cf-v4-ddns.sh >/dev/null 2>&1
* * * * * sleep 30 && /root/cf-v4-ddns.sh >/dev/null
0 1,7,17 * * * cd /root/China-Telecom-Helper_linux_386/ && ./China-Telecom-Helper_linux_386
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
"/tmp/crontab.kquIcC" 3L, 191C

**Comment by chenv12** [comment]
好了，添加进去了，不用Windows是因为脚本检查手机号和sign值一直没有成功过

**Comment by insoxin** [comment]
> 好了，添加进去了，不用Windows是因为脚本检查手机号和sign值一直没有成功过

这没啥区别的啊,看你Linux也没成功,你重新抓下包

**Comment by chenv12** [comment]
挂在Linux上，就可以不用管了。

**Comment by chenv12** [comment]
> > 好了，添加进去了，不用Windows是因为脚本检查手机号和sign值一直没有成功过
> 
> 这没啥区别的啊，看你Linux也没成功，你重新抓下包

手动不会抓。哈哈

**Comment by insoxin** [comment]
> 挂在Linux上，就可以不用管了。

要管的,看其他网友反馈sign值有的有效期二十分,有的十分钟,还有一分钟有效期..失效了需要更新

**Comment by chenv12** [comment]
> > 挂在Linux上，就可以不用管了。
> 
> 要管的，看其他网友反馈sign值有的有效期二十分，有的十分钟，还有一分钟有效期..失效了需要更新

问题是我现在一直没成功。我只会网页抓COOk

**Comment by insoxin** [comment]
https://github.com/insoxin/China-Telecom-Helper/wiki/一些数据值的抓包教程



这里看到吗？是不详细吗

**Comment by chenv12** [comment]
[root@localhost China-Telecom-Helper_linux_386]# ./China-Telecom-Helper_linux_386

中国电信助手 v1.0.12 For:https://t.me/ChinaTelecomHelper


免费使用,禁止买卖,仅限用于学习和研究目的；不得用于商业或者非法用途，否则，一切后果请用户自负。您必须在下载后的24个小时之内，从您的电脑中彻底删除。


正在解析配置文件

Users: 1

配置已完成解析

未开启授权自动化
2023/03/11 20:07:41 开始请求电信客户端
2023/03/11 20:07:41 出错了,请检查手机号和sign值是否有效后重试或更新到最新版本.

**Comment by chenv12** [comment]
安卓: HttpCanary(小黄鸟)  运行抓吧，电信APP就没有网络

**Comment by chenv12** [comment]
苹果IOS没有机器测试

**Comment by insoxin** [comment]
> 安卓: HttpCanary(小黄鸟) 运行抓吧，电信APP就没有网络

进去金豆乐园后 再开启抓包 然后点击喂食,关闭抓包

**Comment by insoxin** [comment]
> 苹果IOS没有机器测试

恰好相反,我没安卓测试,经验全靠朋友提供

**Comment by chenv12** [comment]
好的，我试试

**Comment by chenv12** [comment]
![1](https://user-images.githubusercontent.com/34930155/224484095-dff08445-9ad9-4628-bcf4-0de628ceff4f.jpg)
![2](https://user-images.githubusercontent.com/34930155/224484100-00b22265-2894-426c-92b0-94f1e147a242.jpg)
安装了还提示安装证书

**Comment by insoxin** [comment]
这不知道了,没用过……

**Comment by chenv12** [comment]
证书搞不定，有时间学学电脑版WiresharkPortable64抓包

**Comment by chenv12** [comment]
![3](https://user-images.githubusercontent.com/34930155/224484590-e396ed56-b940-4a37-9023-0be894c92a86.jpg)
![4](https://user-images.githubusercontent.com/34930155/224484602-cbf6d339-ccd8-472c-ba27-ce9cfd5c03ed.jpg)

**Comment by chenv12** [comment]
点COOkie？

**Comment by insoxin** [comment]
> 点COOkie？

点请求

**Comment by insoxin** [comment]
另外不是你这个链接,其他的你看看,看哪个链接里有sign

**Comment by chenv12** [comment]
> 另外不是你这个链接,其他的你看看,看哪个链接里有sign

链接里面包含sign？

**Comment by insoxin** [comment]
> > 另外不是你这个链接,其他的你看看,看哪个链接里有sign
> 
> 链接里面包含sign？

是请求头啊亲   wiki里很清楚了吧

**Comment by chenv12** [comment]
找到了，哈哈，还是得看教程

**Comment by chenv12** [comment]
[root@localhost China-Telecom-Helper_linux_386]# ./China-Telecom-Helper_linux_386

中国电信助手 v1.0.12 For:https://t.me/ChinaTelecomHelper


免费使用,禁止买卖,仅限用于学习和研究目的；不得用于商业或者非法用途，否则，一切后果请用户自负。您必须在下载后的24个小时之内，从您的电脑中彻底删除。


正在解析配置文件

Users: 1

配置已完成解析

未开启授权自动化
2023/03/11 20:48:47 开始请求电信客户端
2023/03/11 20:48:47 更新User-Agent等值成功
2023/03/11 20:48:47 重新序列化
2023/03/11 20:48:47 重新写入config.json


最新版本:1.0.12更新时间:2023-03-10T11:59:05Z
未开启自动更新,自动跳过


开始获取北京时间:2023-03-11 20:48:50 1678538930738

话费兑换:
开始800金豆兑换5元话费(每月两次):未找到参数设置,自动跳过
开始400金豆兑换2元话费(每月两次):未找到参数设置,自动跳过
开始200金豆兑换1元话费(每月三次):未找到参数设置,自动跳过
开始200金豆兑换1元话费(每连签七天可兑换一次):未找到参数设置,自动跳过
开始200金豆兑换1元话费(每月三次):未找到参数设置,自动跳过


会员兑换:
开始240金豆兑换5元网易严选纯享季卡:未找到参数设置,自动跳过
开始1000金豆兑换优酷视频会员月卡:未找到参数设置,自动跳过
开始600金豆兑换腾讯视频会员周卡:未找到参数设置,自动跳过
开始300金豆兑换芒果tv会员周卡:未找到参数设置,自动跳过
开始500金豆兑换爱音乐会员月卡:未找到参数设置,自动跳过


开始喂食任务
开始第1次喂食:今天已达到最大喂食次数
开始第2次喂食:今天已达到最大喂食次数
开始第3次喂食:今天已达到最大喂食次数
开始第4次喂食:今天已达到最大喂食次数
开始第5次喂食:今天已达到最大喂食次数
开始第6次喂食:今天已达到最大喂食次数
开始第7次喂食:今天已达到最大喂食次数
开始第8次喂食:今天已达到最大喂食次数
开始第9次喂食:今天已达到最大喂食次数
开始第10次喂食:今天已达到最大喂食次数


金豆任务
登录任务+5金豆
查看权益中心+5金豆
查看我的云盘+10金豆
打开消息+100金豆
当日分享+50金豆
访问宽带余额+15金豆
访问我的宽带+15金豆
查看装修进度+15金豆
查看我的金豆+5金豆
观看直播15s+5金豆 参数解析错误
查看我的订单+5金豆
查看视频彩铃+10金豆


每月金豆领取:


开始自定义任务

开始执行第1个自定义任务:

开始执行第2个自定义任务:


所有任务执行完毕,剩余金豆935
2023/03/11 20:49:34 程序将在清理后台进程后自动关闭.(部分任务已完成客户端仍显示未完成,具体请以金豆历史记录为准.)

**Comment by insoxin** [comment]
APP查看京豆记录,以这为准

**Comment by chenv12** [comment]
未开启授权自动化
这个功能有什么用处？

**Comment by chenv12** [comment]
好像没领取到：（

**Comment by insoxin** [comment]
> 好像没领取到：（

金豆记录你截图

**Comment by chenv12** [comment]
视频，直播金豆都没有领取

**Comment by insoxin** [comment]
……

**Comment by chenv12** [comment]
![1](https://user-images.githubusercontent.com/34930155/224485834-376aa539-0b4d-42a3-9d25-578935d3ba71.jpg)

**Comment by chenv12** [comment]
感谢作者大大，辛苦了
