### ISSUE TITLE
Windows配置手机号和sign，报错。

### ISSUE THREAD

**Issue by vipnetant** [insoxin/China-Telecom-Helper#116]
版本：1.0.12

报错提示

`未开启授权自动化
2023/03/12 16:43:32 开始请求电信客户端
2023/03/12 16:43:32 出错了,请检查手机号和sign值是否有效后重试或更新到最新版本.`

sign是通过[https://api.isoyu.com/10000/user/send/](https://api.isoyu.com/10000/user/send/)获取的。

config.json内容如下：

> {
	"users": [{
		"AutoUpdate": "false",
		"systime": "http://cloudflare.api.isoyu.com/time/SysTime/?appCode=B586A14C4EC466D33682F8626CCB3794&auturl=api.isoyu.com&num=13",
		"Authorization": "false",
		"alipay": "",
		"sign": "3e5268eb7************35dee53",
		"ua": "",
		"Monthlybeans": "",
		"cookie": "cookie",
		"Notice": "https://t.me/ChinaTelecomHelper",
		"phone": 153***手机号码***98,
		"para": [{
			"setting": "true"
		}, {
			"para156": ""
		}, {
			"para256": ""
		}, {
			"para768": ""
		}],
		"Paradise": [{
			"Polymerize": ""
		}, {
			"Polymerize": ""
		}, {
			"Polymerize": ""
		}]
	}]
}

**Comment by insoxin** [comment]
![image](https://user-images.githubusercontent.com/19371836/224534289-3d84326a-4f02-429b-bff2-b253f766004a.png)

**Comment by vipnetant** [comment]
意思是用平台接码会有问题，最保险是自己抓包？

**Comment by insoxin** [comment]
> 意思是用平台接码会有问题，最保险是自己抓包？

对,模拟的人多容易错乱
