### ISSUE TITLE
好东西，就是sign时间太短了,但我总感觉还有一些功能不会用的。

### ISSUE THREAD

**Issue by Tteamtd** [insoxin/China-Telecom-Helper#118]
登录失败,授权无效(是不是有自动登录功能呀?)
话费兑换:
开始800金豆兑换5元话费(每月两次):  未找到参数设置,自动跳过

未找到参数设置,自动跳过，（是要设置什么参数才能自动兑换吗？）

**Comment by chenj7918** [comment]
> 登录失败,授权无效(是不是有自动登录功能呀?) 话费兑换: 开始800金豆兑换5元话费(每月两次): 未找到参数设置,自动跳过
> 
> 未找到参数设置,自动跳过，（是要设置什么参数才能自动兑换吗？）

你肯定没看前言部分，哈哈哈

**Comment by shen115** [comment]
sing失效太快了，不知道能不能考虑加个心跳保持在线。

**Comment by insoxin** [comment]
> sing失效太快了，不知道能不能考虑加个心跳保持在线。

这个想法很好,就是需要24小时一直挂了

**Comment by shen115** [comment]
那无所谓，关键是包活，心跳更新cookie就行了

**Comment by shen115** [comment]
还有加个建议，多账号功能

**Comment by insoxin** [comment]
> 还有加个建议，多账号功能

这个最初支持,有人拿来收费代挂,以后不会支持

**Comment by shen115** [comment]
限制个数3-5个，一般一家人也就这几个号

**Comment by insoxin** [comment]
> 限制个数3-5个，一般一家人也就这几个号

那这更容易了,多复制一份配置文件就行,就是给哪些几百个号代挂的增加困难

**Comment by shen115** [comment]
在你客户端限制就行了

**Comment by shen115** [comment]
心跳保持在线功能抓紧添加
