### ISSUE TITLE
请问怎么添加多个手机号？

### ISSUE THREAD

**Issue by zzzddd897** [insoxin/China-Telecom-Helper#12]

**Comment by insoxin** [comment]
不支持多账户,就是为了防止收费代挂的 我把自动抢的也删了  这年头很危险的.

**Comment by aaron0713** [comment]
> 不支持多账户,就是为了防止收费代挂的 我把自动抢的也删了,也拒绝了任何打赏 这年头很危险的.

config.json里面的user不是个数组吗？写多个user无效？

**Comment by insoxin** [comment]
> > 不支持多账户,就是为了防止收费代挂的 我把自动抢的也删了,也拒绝了任何打赏 这年头很危险的.
> 
> config.json里面的user不是个数组吗？写多个user无效？

编译放出来的我都删了,我留给自己用的  不能保证不被其他人恶意售卖哇  我真的怕

**Comment by aaron0713** [comment]
> 

嗯，理解
