### ISSUE TITLE
内测群链接是多少？

### ISSUE THREAD

**Issue by chenv12** [insoxin/China-Telecom-Helper#122]
老大加我进内测群。或者发个内测版本给我5828171@qq.com谢谢

**Comment by huwt8** [comment]
同求，tg频道也没看见内测邀请链接啊

**Comment by P3R5T7U9** [comment]
> 同求，tg频道也没看见内测邀请链接啊

时隔10个多月，打扰下；
不知老哥你现在还在“insoxin”大佬的TG频道里么？？我今天才翻到此仓库，看“insoxin”大佬最后对此仓库更新停止在23年3月份，我在浏览器打开ReadMe中提到的TG频道地址，如下截图所示：
!()[https://i.ibb.co/SwRKkLH/IMG-20240121-165347.jpg]

猜测“Insoxin”大佬早将官方TG频道改名或设置为私有频道，如果老哥你目前还在TG频道里，麻烦回复甩下“Insoxin”大佬创建的TG频道最新地址，也想加下；

另外，如果老哥你之后找到“中国电信助手”的内测群地址，麻烦也回复指个路呗😭
(小声：今天用此仓库的Release中23年3月的exe文件，运行直接报错，翻了下Issue区，估计也都失效了，也想上车使用内测版“中国电信助手”)

**Comment by P3R5T7U9** [comment]
> 老大加我进内测群。或者发个内测版本给我[5828171@qq.com](mailto:5828171@qq.com)谢谢

时隔10个多月，打扰下；

不知老哥你之后有收到“Insoxin”大佬通过邮件向你发送“中国电信助手”的内测版或内测群地址么？？如果有收到的话，麻烦也向我的邮箱：[lws226691zhao@163.com](mailto:lws226691zhao@163.com)转下当初收到的邮件内容，也想加下内测群，试试内测版工具效果😖
(小声：我今天才翻到此仓库，直接下载使用用此仓库的Release中23年3月的exe文件，打开运行后直接报错，翻了下Issue区历史反馈，exe文件早都失效了。。。

继而翻到老哥你在去年3月发的几条关于内测群的Issue，才知道“Insoxin”大佬在去年3月开始将“中国电信助手”转为内测群分享，也想上车内测版包，但我一直没找到“Insoxin”大佬的内测群地址。。。)

**Comment by chenv12** [comment]
大佬当初也没有回复我发自我的荣耀手机-------- 原始邮件 --------发件人： Mayuu酱重症患者 ***@***.***>日期： 2024年1月21日周日 17:17收件人： insoxin/China-Telecom-Helper ***@***.***>抄送： chenv12 ***@***.***>, Author ***@***.***>主    题： Re: [insoxin/China-Telecom-Helper] 内测群链接是多少？ (Issue #122)

***@***.***谢谢

时隔10个多月，打扰下；
***@***.***转下当初收到的邮件内容，也想加下内测群，试试内测版工具效果😖
(小声：我今天才翻到此仓库，直接下载使用用此仓库的Release中23年3月的exe文件，打开运行后直接报错，翻了下Issue区历史反馈，exe文件早都失效了。。。
继而翻到老哥你在去年3月发的几条关于内测群的Issue，才知道“Insoxin”大佬在去年3月开始将“中国电信助手”转为内测群分享，也想上车内测版包，但我一直没找到“Insoxin”大佬的内测群地址。。。)

**Comment by P3R5T7U9** [comment]
> 大佬当初也没有回复我发自我的荣耀手机-------- 原始邮件 --------发件人： Mayuu酱重症患者 ***@***.***>日期： 2024年1月21日周日 17:17收件人： insoxin/China-Telecom-Helper ***@***.***>抄送： chenv12 ***@***.***>, Author ***@***.***>主 题： Re: [insoxin/China-Telecom-Helper] 内测群链接是多少？ (Issue #122) ***@***.***谢谢 时隔10个多月，打扰下； ***@***.***转下当初收到的邮件内容，也想加下内测群，试试内测版工具效果😖 (小声：我今天才翻到此仓库，直接下载使用用此仓库的Release中23年3月的exe文件，打开运行后直接报错，翻了下Issue区历史反馈，exe文件早都失效了。。。 继而翻到老哥你在去年3月发的几条关于内测群的Issue，才知道“Insoxin”大佬在去年3月开始将“中国电信助手”转为内测群分享，也想上车内测版包，但我一直没找到“Insoxin”大佬的内测群地址。。。) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

woc，老哥你回复速度真滴快，刚向你发完提问才过了十来分钟，老哥你就回复了，还以为老哥你这条Issue都创建过去10个月，而“Insoxin”大佬一直没回复老哥你这条Isssue，当天就关闭了，所以早就不管这条Isssue有无回复，半小时前我发完提问，猜测老哥你看到后都过去许久了。。。

感谢老哥你的回复说明，有个此工具的平替问题已通过老哥你这条Issue当初提到的个人企鹅邮箱发邮件给老哥你了，不想在这边公开讨论了，麻烦老哥在个人企鹅邮箱尽快查收我发的邮件

**Comment by GitCourser** [comment]
> 感谢老哥你的回复说明，有个此工具的平替问题已通过老哥你这条Issue当初提到的个人企鹅邮箱发邮件给老哥你了，不想在这边公开讨论了，麻烦老哥在个人企鹅邮箱尽快查收我发的邮件

老哥能不能给我也发下平替工具(官网, tg, 群),感谢.
3290468281@qq.com
