### ISSUE TITLE
获取时间错误

### ISSUE THREAD

**Issue by FellBan** [insoxin/China-Telecom-Helper#14]
![image](https://user-images.githubusercontent.com/13709020/169633918-f43512c3-6eb4-4491-8636-cd462bc2e7c8.png)

**Comment by insoxin** [comment]
配置文件中修改https   为http

**Comment by FellBan** [comment]
改了变这样子了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "insoxin/China-Telecom-Helper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月21日(星期六) 中午11:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [insoxin/China-Telecom-Helper] 获取时间错误 (Issue #14)





 
配置文件中修改https   为http

**Comment by insoxin** [comment]
> 改了变这样子了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "insoxin/China-Telecom-Helper" ***@***.***&gt;; 发送时间:&nbsp;2022年5月21日(星期六) 中午11:37 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [insoxin/China-Telecom-Helper] 获取时间错误 (Issue #14) 配置文件中修改https 为http — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

没看到图

**Comment by FellBan** [comment]
> > 改了变这样子了
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "insoxin/China-Telecom-Helper" _**@**_._**>; 发送时间: 2022年5月21日(星期六) 中午11:37 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [insoxin/China-Telecom-Helper] 获取时间错误 (Issue #14) 配置文件中修改https 为http — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 没看到图

![image](https://user-images.githubusercontent.com/13709020/169634138-042f6da7-873f-4ae9-9c49-40cd3aa104df.png)

**Comment by insoxin** [comment]
> > > 改了变这样子了
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: "insoxin/China-Telecom-Helper" _**@**_._**>; 发送时间: 2022年5月21日(星期六) 中午11:37 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [insoxin/China-Telecom-Helper] 获取时间错误 (Issue #14) 配置文件中修改https 为http — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> > 
> > 
> > 没看到图
> 
> ![image](https://user-images.githubusercontent.com/13709020/169634138-042f6da7-873f-4ae9-9c49-40cd3aa104df.png)

`curl -k -X POST -H 'Content-Type: application/json;charset=utf-8'  'http://clodflare.api.isoyu.com/time/SysTime/?appCode=B586A14C4EC466D33682F8626CCB3794&auturl=api.isoyu.com&num=13'`

这个返回什么截下图

**Comment by FellBan** [comment]
> 

![image](https://user-images.githubusercontent.com/13709020/169635677-998e9e21-3168-4bb8-b749-7e0cb2c5eaf3.png)

**Comment by insoxin** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/13709020/169635677-998e9e21-3168-4bb8-b749-7e0cb2c5eaf3.png)

你这IP被标记了 cf拦截了  用这个国内的吧http://api.isoyu.com/time/SysTime/?appCode=B586A14C4EC466D33682F8626CCB3794&auturl=api.isoyu.com&num=13
