### ISSUE TITLE
系统类型

### ISSUE THREAD

**Issue by Chenxy-1999** [insoxin/China-Telecom-Helper#16]
有没有arm32的

**Comment by insoxin** [comment]
好,稍等

**Comment by Chenxy-1999** [comment]
谢谢

**Comment by insoxin** [comment]
> 谢谢

https://github.com/insoxin/China-Telecom-Helper/releases/tag/1.0.5  大佬试试看可以不,我没真机测试

**Comment by Chenxy-1999** [comment]
谢谢，回家测试下

**Comment by Chenxy-1999** [comment]
可以用，就是聚合任务失败，谢谢大佬

**Comment by insoxin** [comment]
> 可以用，就是聚合任务失败，谢谢大佬

返回截图发下 听你说其他 正常,如果其他正常,并且自定义任务500错误那是para值错了

![image](https://user-images.githubusercontent.com/19371836/169649517-040f5122-fc3d-462f-8fb2-c2ba42148ed7.png)

**Comment by insoxin** [comment]
> 可以用，就是聚合任务失败，谢谢大佬

详细补充了教程 https://github.com/insoxin/China-Telecom-Helper/wiki/%E4%B8%80%E4%BA%9B%E6%95%B0%E6%8D%AE%E5%80%BC%E7%9A%84%E6%8A%93%E5%8C%85%E6%95%99%E7%A8%8B#para

**Comment by Chenxy-1999** [comment]
![image](https://user-images.githubusercontent.com/63447222/169650051-12068940-8eb6-463f-88b4-4d15d752c1c6.png)

**Comment by insoxin** [comment]
> ![image](https://user-images.githubusercontent.com/63447222/169650051-12068940-8eb6-463f-88b4-4d15d752c1c6.png)

para 是512个字符么,看我上面更新的新的抓包教程,换个了链接

**Comment by Chenxy-1999** [comment]
不是 768个

**Comment by insoxin** [comment]
> 不是 768个

卧槽,哪里抓到的,方便截图下吗

**Comment by Chenxy-1999** [comment]
![933B945FCD22617AD25812FE75DCE386](https://user-images.githubusercontent.com/63447222/169650360-92264cf6-2fd9-4be1-8cf1-5a9bd9b3b8e7.jpg)
![3895E87C44A136A10A34F8159FE00512](https://user-images.githubusercontent.com/63447222/169650363-e37c79c5-143f-4230-b171-36ebbdce3c05.jpg)

**Comment by Chenxy-1999** [comment]
抓的时候我看见第一个有 就复制了

**Comment by insoxin** [comment]
> 抓的时候我看见第一个有 就复制了

配置文件给我邮箱insoxin@qq.com发一份,我手动curl一下试试

**Comment by insoxin** [comment]
> 抓的时候我看见第一个有 就复制了

我找到原因了.para 我去更新新版本
![image](https://user-images.githubusercontent.com/19371836/169653549-1ad51c90-0925-45d1-90da-c3b822ccfe03.png)

**Comment by insoxin** [comment]
新版本更新了,大佬,应该可以了  把多个para值分开了
