### ISSUE TITLE
有 open source 版本吗？从安全角度考虑，不亚于提供 支付宝 银行卡密码

### ISSUE THREAD

**Issue by tutugreen** [insoxin/China-Telecom-Helper#24]
毕竟是登录运营商的，从安全角度考虑，不亚于提供 支付宝 银行卡 密码/各类验证码，很难信任来源不明/未受审查的二进制。

**Comment by insoxin** [comment]
看到的一句话
非必要不开源，非必要不编程，切实做好ide激活问责制，从源头起阻断非法代码传播链，尽快摸清底数，控制增量;发现一行代码，处理一行代码，争取早日做到开源面清零。

而且 法律有条 帮信罪 了,我要是国外我就开源了

**Comment by limoruirui** [comment]
> 毕竟是登录运营商的，从安全角度考虑，不亚于提供 支付宝 银行卡 密码/各类验证码，很难信任来源不明/未受审查的二进制。

其实还好 电信app也不靠cookie验证 最多就是提供了手机号 不过就这项目目前的完成度来说 也没必要弄就是了 半成品都说不上吧

**Comment by insoxin** [comment]
> > 毕竟是登录运营商的，从安全角度考虑，不亚于提供 支付宝 银行卡 密码/各类验证码，很难信任来源不明/未受审查的二进制。
> 
> 其实还好 电信app也不靠cookie验证 最多就是提供了手机号 不过就这项目目前的完成度来说 也没必要弄就是了 半成品都说不上吧

说的非常对啊,要不是我偷偷挂了几年,白嫖了几千话费多到用不完.我也没必要放出来.大佬怎么会看得上这残次品,分分钟自己就做了

**Comment by ChenZIDu** [comment]
确实，这个抢话费也太难了

**Comment by overlords** [comment]
建议担心作者作恶，有两方法，
 1. 自己开发一套
 2. 10w买作者源码
