### ISSUE TITLE
不懂就问，这个怎么在Mac系统运行

### ISSUE THREAD

**Issue by winterwd** [insoxin/China-Telecom-Helper#29]
如题

**Comment by insoxin** [comment]
https://github.com/insoxin/China-Telecom-Helper/releases

**Comment by winterwd** [comment]
> https://github.com/insoxin/China-Telecom-Helper/releases

眼瞎，找到了！linux_386 这个

**Comment by 42vio** [comment]
请问你用的哪个版本的，我运行 linux_386 报错 no such file or directory:
