### ISSUE TITLE
获取时间的api被定向到反诈网站了，请问如果获取新的时间api

### ISSUE THREAD

**Issue by ycblog** [insoxin/China-Telecom-Helper#30]

**Comment by insoxin** [comment]
不是有备选么？

**Comment by insoxin** [comment]
http://cloudflare.api.isoyu.com/time/SysTime/?appCode=B586A14C4EC466D33682F8626CCB3794&auturl=api.isoyu.com&num=13

**Comment by newtool** [comment]
这个网站也不行了

**Comment by insoxin** [comment]
> 这个网站也不行了

卧槽感谢提醒,这玩意备案还能掉
