### ISSUE TITLE
运行软件 闪退

### ISSUE THREAD

**Issue by wei37544** [insoxin/China-Telecom-Helper#35]
设备电脑win7系统64位，不知道是不是我没有设置好，还是没抓对，运行软件就闪退，还是有些不懂，请问cookie是填入几百字符那种，还是填入s_fid=后面的一串字符，这两种我都尝试填入还是不做任务闪退，请大佬再指点一下

**Comment by eon-x** [comment]
启动，配置文件读取完，获取北京时间闪退，大佬
![111](https://user-images.githubusercontent.com/11568221/205211493-120b1aa7-0667-4420-9bb8-490aa18e8bcb.png)
