### ISSUE TITLE
黄鸟一挂，中国电信直接没网

### ISSUE THREAD

**Issue by lijingbo666** [insoxin/China-Telecom-Helper#36]
安卓  MIUI13  root  黄鸟挂上中国电信直接没网

**Comment by gzmars** [comment]
我是米11 root ，没开小黄鸟，安装电信后都就运行不了，卡死在启动界面

**Comment by lijingbo666** [comment]
.0和pem安装一个就好了，我的米10pro银行软件都能打开，就是挂上黄鸟中国电信没网
