### ISSUE TITLE
"AutoUpdate": "flase"是不是打错了？

### ISSUE THREAD

**Issue by ChenZIDu** [insoxin/China-Telecom-Helper#39]
## 下列各问题请注意打码隐藏重要信息

**描述错误**
清晰简洁地描述错误是什么。

**复制**
重现行为的步骤：
1. 转到“...”
2. 点击“....”
3. 向下滚动到“....”
4.查看错误

**预期行为**
对您期望发生的事情进行清晰简洁的描述。

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
**软件版本**
v1.0.0
**congfig.json文件配置**
```
{
	"users": [{
		        "AutoUpdate": "flase",
			"cookie": "cookie",
			"para": "para",
			"phone": 13800138000,
			"monthlybeans": "monthly beans",
			"Paradise": [{
				"setting": "true"
			}, {
				"Polymerize": "Polymerize"
			}, {
				"Polymerize": "Polymerize"
			}],
			"systime": "http://cloudflare.api.isoyu.com/time/SysTime/?appCode=B586A14C4EC466D33682F8626CCB3794&auturl=api.isoyu.com&num=13",
			"github": "https://github.com/insoxin/China-Telecom-Helper"

		}

	]
}
```

**桌面（请填写以下信息）：**
  - 操作系统：[例如 iOS]
  - 浏览器 [例如 chrome, safari]
  - 版本 [例如 22]

**智能手机（请填写以下信息）：**
  - 设备：[例如 iPhone 6]
  - 操作系统：[例如 iOS8.1]
  - 浏览器 [例如 chrome, safari]
  - 版本 [例如 22]

**附加上下文**
在此处添加有关该问题的任何其他上下文。

**Comment by insoxin** [comment]
对,打错了,哈哈哈哈我是个菜鸡

**Comment by insoxin** [comment]
我刚搜了下,貌似没错,两个都能用

**Comment by ChenZIDu** [comment]
如果是true的话，更新是更新哪部分，json文件会被覆盖吗

**Comment by ChenZIDu** [comment]
喂食显示参数错误，是哪里配置原因吗
![image](https://user-images.githubusercontent.com/49174343/170173760-3637f7e9-0331-4278-95e4-449f21790191.png)

**Comment by insoxin** [comment]
> 如果是true的话，更新是更新哪部分，json文件会被覆盖吗

主程序,配置config不更新

**Comment by insoxin** [comment]
> 喂食显示参数错误，是哪里配置原因吗 ![image](https://user-images.githubusercontent.com/49174343/170173760-3637f7e9-0331-4278-95e4-449f21790191.png)
wiki

**Comment by ChenZIDu** [comment]
> > 喂食显示参数错误，是哪里配置原因吗 ![image](https://user-images.githubusercontent.com/49174343/170173760-3637f7e9-0331-4278-95e4-449f21790191.png)
> > wiki

我去找找

**Comment by ChenZIDu** [comment]
这个参数解析错误，是不是因为我任务已经完成了导致的

**Comment by ChenZIDu** [comment]
应该是，失败的都是我完成的任务，明天再看看

**Comment by insoxin** [comment]
> 这个参数解析错误，是不是因为我任务已经完成了导致的

不是,就是参数填错了,已做任务会提示达到喂食上限

**Comment by ChenZIDu** [comment]
> > 这个参数解析错误，是不是因为我任务已经完成了导致的
> 
> 不是,就是参数填错了,已做任务会提示达到喂食上限

我看每个接口cookie都有不同的地方，不知道是不是cookie缺少参数
