### ISSUE TITLE
可否提供 docker 或 podman 之类？

### ISSUE THREAD

**Issue by laincat** [insoxin/China-Telecom-Helper#4]
感激

**Comment by insoxin** [comment]
已经做了,然后想着主要还是抓包流程比较困难,觉得不太有意义就没放出来

比如在Linux 直接
一行代码
```
./China-Telecom-Helper
```
就行了,如果你是想要自动任务的,也可以完全参考redame

[定时执行](https://github.com/insoxin/China-Telecom-Helper#%E5%AE%9A%E6%97%B6%E6%89%A7%E8%A1%8C)


都蛮简单的,或者有我遗漏的点,可以补充一下

**Comment by xxzhil** [comment]
要是把docker弄好再加个面板就好了

**Comment by insoxin** [comment]
> 要是把docker弄好再加个面板就好了

我认为现在已经是最简单的方法,Linux,win都是一键

**Comment by xxzhil** [comment]
> > 要是把docker弄好再加个面板就好了>> 我认为现在已经是最简单的方法，Linux，win都是一键
主要是我身边没电脑。实在不好

**Comment by insoxin** [comment]
> 要是把docker弄好再加个面板就好了>> 我认为现在已经是最简单的方法，Linux，win都是一键
> 主要是我身边没电脑。实在不好

那你什么设备执行呢？安卓手机?还是路由器

**Comment by wuzhanshen** [comment]
> > 把弄弄好现在我认为没有个面板好了
> > >>
> 
> 那你什么设备？安卓手机？还是路由器执行呢？

大佬，能支持青龙面板吗，或者x86路由 openwrt ，联通可以签到可以做嘛？

**Comment by insoxin** [comment]
> > > 把弄弄好现在我认为没有个面板好了
> > > > >
> > 
> > 
> > 那你什么设备？安卓手机？还是路由器执行呢？
> 
> 大佬，能支持青龙面板吗，或者x86路由 openwrt ，联通可以签到可以做嘛？
#2 
路由器支持的.没联通号

**Comment by xxzhil** [comment]
> > 要是把docker弄好再加个面板就好了>> 我认为现在已经是最简单的方法，Linux，win都是一键主要是我身边没有电脑。实在不好>> 那你什么设备执行呢？安卓手机？还是路由器
我是ios利用ssh进入docker。。。。。或者有配置面板也好喔

**Comment by xxzhil** [comment]
> > 要是把docker弄好再加个面板就好了>> 我认为现在已经是最简单的方法，Linux，win都是一键
> > 主要是我身边没电脑。实在不好
> 
> 那你什么设备执行呢？安卓手机?还是路由器

新手。习惯用ssh进入云服务器。你打包成这样，主要我不会弄指令

**Comment by xxzhil** [comment]
> 

谢谢。我知道怎么操作了。

**Comment by gxm512** [comment]
真心需要dokcer或者直接青龙面板的方式

**Comment by a65101855** [comment]
> 真心需要dokcer或者直接青龙面板的方式

ME TOO！  windows会闪退，现在用DOCKER得比用LINUX的多了
