### ISSUE TITLE
cookie

### ISSUE THREAD

**Issue by ChenZIDu** [insoxin/China-Telecom-Helper#41]
cookie都需要哪些参数呢，感觉说的不是很清楚，上面写的是所有，但是我看你图打码的部分就一行，我看如果复制所有的cookie信息起码要六七行。
![image](https://user-images.githubusercontent.com/49174343/170196368-e3c55132-b936-4b78-8d35-38b58b1494f4.png)
不知道参数解析错误是不是这个cookie设置错误导致的

**Comment by insoxin** [comment]
para768这个值是不是768字符

**Comment by ChenZIDu** [comment]
是的，para768值来自/jt-sign/paradise/getConversionRights接口
para512值来自/jt-sign/api/home/homeInfo接口

**Comment by ChenZIDu** [comment]
512的接口好像错了，我试试wiki的给错了

**Comment by insoxin** [comment]
> 512的接口好像错了，我试试wiki的给错了

wiki哪里错了,我改下大概多少行或者哪个一块

**Comment by insoxin** [comment]
1.0.6版本吗

**Comment by insoxin** [comment]
> > 512的接口好像错了，我试试wiki的给错了
> 
> wiki哪里错了,我改下大概多少行或者哪个一块 不是的，wiki上我好像给错接口了，我是git下来的

喂食我用的para768这个值,我去找找试试我的行不行,也许官方改接口了

**Comment by ChenZIDu** [comment]
> > > 512的接口好像错了，我试试wiki的给错了
> > 
> > 
> > wiki哪里错了,我改下大概多少行或者哪个一块 不是的，wiki上我好像给错接口了，我是git下来的
> 
> 喂食我用的para768这个值,我去找找试试我的行不行,也许官方改接口了

我再看看768，估计是哪里错了我再试试抓一下看看

**Comment by ChenZIDu** [comment]
> 1.0.6版本吗

怎么区分我当前版本呀，我运行显示的是v0.1，我试一下下载新的已经打包的main文件试试

**Comment by insoxin** [comment]
> > 1.0.6版本吗
> 
> 怎么区分我当前版本呀，我运行显示的是v0.1，我试一下下载新的已经打包的main文件试试

噗,你是下错了,我就感觉很奇怪https://github.com/insoxin/China-Telecom-Helper/releases/ 这里下

**Comment by ChenZIDu** [comment]
= = 师傅你怎么push上去的是旧的，我傻了。我下载了打包的，发现可以运行了，谢谢师傅

**Comment by insoxin** [comment]
> = = 师傅你怎么push上去的是旧的，我傻了。我下载了打包的，发现可以运行了，谢谢师傅

没有的哇 readme上有写,你是第一个下错的.

**Comment by ChenZIDu** [comment]
我以为git clone下来的是最新的= = 我好像想起来了，我昨天git的时候是几年前的版本

**Comment by ChenZIDu** [comment]
说句题外话，这个兑换手动兑换需要定时抢吗

**Comment by insoxin** [comment]
> 我以为git clone下来的是最新的= = 我好像想起来了，我昨天git的时候是几年前的版本

大部分git是最新的,但是部分人不会编译,我索性顺手编译好了.主main就懒得更新了.也怪我习惯不好.我去修改一下

**Comment by insoxin** [comment]
> 说句题外话，这个兑换手动兑换需要定时抢吗

对的,如果动手能力强可以自己写

**Comment by ChenZIDu** [comment]
算了，我就手动抢吧，手动应该抢得到吧

**Comment by insoxin** [comment]
> 算了，我就手动抢吧，手动应该抢得到吧

之前可以,现在我看star已经400了,大概率有点难.不过每人有限制次数可以了解一下.我自动抢了多年了.还没失手过.现在余额过千了用不完就放出来脚本了.
