### ISSUE TITLE
哎，这个10点兑换太难了，数量少，估计都是脚本请求的接口

### ISSUE THREAD

**Issue by ChenZIDu** [insoxin/China-Telecom-Helper#47]

**Comment by oqo0opo** [comment]
确实，点击按钮无响应。

**Comment by insoxin** [comment]
最初的测试版支持自动抢的,有一批人在用,,,

**Comment by ChenZIDu** [comment]
0.01版本嘛

> 最初的测试自动抢的有版支持人用,,,

本来想用0.1版本的，但是前几天还看到兑换的配置，好像改了wiki没找到兑换的json配置了

**Comment by ChenZIDu** [comment]
师傅方便私聊0.1 json么，我去用0.1的试试

**Comment by insoxin** [comment]
不行啊,害怕.自己可以动手搞个,别传播

**Comment by ChenZIDu** [comment]
如果是计划任务运行的话，好像会报找不到json，有点奇怪
![image](https://user-images.githubusercontent.com/49174343/170616457-e4263b74-5452-44a6-8dc8-3c0cecef6f5c.png)

**Comment by insoxin** [comment]
> 如果是计划任务运行的话，好像会报找不到json，有点奇怪 ![image](https://user-images.githubusercontent.com/49174343/170616457-e4263b74-5452-44a6-8dc8-3c0cecef6f5c.png)

需要先cd

**Comment by ChenZIDu** [comment]
> 

自己用呀总共就几千份话费= =，我感觉前两天还在wiki上看到初版兑换的json配置

**Comment by ChenZIDu** [comment]
> > 如果是计划任务运行的话，好像会报找不到json，有点奇怪 ![image](https://user-images.githubusercontent.com/49174343/170616457-e4263b74-5452-44a6-8dc8-3c0cecef6f5c.png)
> 
> 需要先cd

我给的是绝对路径，应该不用吧，找json用的是相对路径嘛

**Comment by insoxin** [comment]
> cd /abc
> ./abcd

cd /abc
./abcd

**Comment by insoxin** [comment]
> > > 如果是计划任务运行的话，好像会报找不到json，有点奇怪 ![image](https://user-images.githubusercontent.com/49174343/170616457-e4263b74-5452-44a6-8dc8-3c0cecef6f5c.png)
> > 
> > 
> > 需要先cd
> 
> 我给的是绝对路径，应该不用吧，找json用的是相对路径嘛

cd /abc
./abcd

**Comment by ChenZIDu** [comment]
测试版的json还有备份嘛~~

**Comment by ChenZIDu** [comment]
不对，测试版0.0.1的json我还有，就是不知道咋配置兑换

**Comment by ChenZIDu** [comment]
不知道是哪个格式的那个参数，之前的wiki还有存档吗师傅~~

**Comment by ChenZIDu** [comment]
师傅试了好多接口，你判断参数是啥呀
![image](https://user-images.githubusercontent.com/49174343/170664825-4568ac06-abd7-425e-840b-4c0a8335507a.png)
我不传播😭

**Comment by onesixsix** [comment]
> 师父试了很多接口，你判断参与数是啥呀 我不传播 ![图片](https://user-images.githubusercontent.com/49174343/170664825-4568ac06-abd7-425e-840b-4c0a8335507a.png)😭

老哥弄懂了吗，交流一下
