### ISSUE TITLE
定时任务无法执行，手动可以执行

### ISSUE THREAD

**Issue by FairyWorld** [insoxin/China-Telecom-Helper#49]
已经修改了可执行权限
chmod +x /xx/China-Telecom-Helper_linux_amd64

crontab如下, 无法自动执行
5 1,7,13,19,11 * * * /xx/China-Telecom-Helper_linux_amd64

手动执行可以
 /xx/China-Telecom-Helper_linux_amd64

**Comment by abcll2019** [comment]
+1

**Comment by insoxin** [comment]
可以先cd
然后执行
