### ISSUE TITLE
抓包获取的

### ISSUE THREAD

**Issue by gzmars** [insoxin/China-Telecom-Helper#50]
iOS用thor抓包，获取的Polymerize放到config.json里都是报错。
请问大家是怎么抓包的？
![image](https://user-images.githubusercontent.com/46783444/170625141-f50c9c47-f90b-4457-8a80-cdd2037b4fc1.png)
![image](https://user-images.githubusercontent.com/46783444/170625405-cc2ff091-1378-483a-b01d-ae2a5d7ea69a.png)
![image](https://user-images.githubusercontent.com/46783444/170625479-2bb7ffcb-0853-4bf8-b848-af95e4c709af.png)

**Comment by insoxin** [comment]
获取到的值,自己本地curl一下检验
