### ISSUE TITLE
刚看到就跑路了吗

### ISSUE THREAD

**Issue by cloverzrg** [insoxin/China-Telecom-Helper#58]
哈哈哈

**Comment by insoxin** [comment]
任务手动都做不了了,不知道是号黑了,还是怎么回事,多人反馈,此时不跑,更待何时

#54

**Comment by PDxtXHd** [comment]
> 任务手动都做不了了,不知道是号黑了,还是怎么回事,多人反馈,此时不跑,更待何时
> 
> #54

不是黑号，因为我两个号都还没来得及抓包测试脚本，照样做不了大部分任务了，感觉是电信疯了
