### ISSUE TITLE
运行成功了，但是任务没有完成

### ISSUE THREAD

**Issue by FairyWorld** [insoxin/China-Telecom-Helper#6]
![image](https://user-images.githubusercontent.com/32956212/169464789-5b9f5cab-cf7d-43c0-a358-4d9edd3674fa.png)
![image](https://user-images.githubusercontent.com/32956212/169464831-a87fbb8e-e0e5-4619-97de-53fa59f773cb.png)

**Comment by insoxin** [comment]
看文档啊,你这都是空白值 [填写完成所有参数,记得试运行一下,返回聚合任务接口请求成功才是成功,空白大几率电信官方服务器出错,并且为保万一,即便返回请求成功,也要去看下金豆历史记录,没有金豆收入就再次查验抓包的参数是否正确](https://github.com/insoxin/China-Telecom-Helper/wiki/%E4%B8%80%E4%BA%9B%E6%95%B0%E6%8D%AE%E5%80%BC%E7%9A%84%E6%8A%93%E5%8C%85%E6%95%99%E7%A8%8B#%E5%A1%AB%E5%86%99%E5%AE%8C%E6%88%90%E6%89%80%E6%9C%89%E5%8F%82%E6%95%B0%E8%AE%B0%E5%BE%97%E8%AF%95%E8%BF%90%E8%A1%8C%E4%B8%80%E4%B8%8B%E8%BF%94%E5%9B%9E%E8%81%9A%E5%90%88%E4%BB%BB%E5%8A%A1%E6%8E%A5%E5%8F%A3%E8%AF%B7%E6%B1%82%E6%88%90%E5%8A%9F%E6%89%8D%E6%98%AF%E6%88%90%E5%8A%9F%E7%A9%BA%E7%99%BD%E5%A4%A7%E5%87%A0%E7%8E%87%E7%94%B5%E4%BF%A1%E5%AE%98%E6%96%B9%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%87%BA%E9%94%99%E5%B9%B6%E4%B8%94%E4%B8%BA%E4%BF%9D%E4%B8%87%E4%B8%80%E5%8D%B3%E4%BE%BF%E8%BF%94%E5%9B%9E%E8%AF%B7%E6%B1%82%E6%88%90%E5%8A%9F%E4%B9%9F%E8%A6%81%E5%8E%BB%E7%9C%8B%E4%B8%8B%E9%87%91%E8%B1%86%E5%8E%86%E5%8F%B2%E8%AE%B0%E5%BD%95%E6%B2%A1%E6%9C%89%E9%87%91%E8%B1%86%E6%94%B6%E5%85%A5%E5%B0%B1%E5%86%8D%E6%AC%A1%E6%9F%A5%E9%AA%8C%E6%8A%93%E5%8C%85%E7%9A%84%E5%8F%82%E6%95%B0%E6%98%AF%E5%90%A6%E6%AD%A3%E7%A1%AE)

**Comment by insoxin** [comment]
而且你图中就加了两个自定义任务,怎么会执行其他任务?  先读文档啊

**Comment by insoxin** [comment]
等我再加个判断网页状态码的功能, 把返回值,全部显示出来

**Comment by FairyWorld** [comment]
> 等我再加个判断网页状态码的功能, 把返回值,全部显示出来

我把所有任务都点了一遍, 抓取的oYid6CPr填入了paradise里面, 像下面一样。还不确定有没有运行成功，因为是我手动完成的
```oYid6CPr=5vcYG3nBCVlh75p_TWA3z_6f8tKBVLKLncBFz8ZL8Y3d2uwVt.R_LpHSJAMeN9Sj2aA5TdkLRAfAUQWLOXoOZMCM09tJ7cX5erpi9IgtzNTea8qF9B_WL9r0Tx374Je76u2ad2tuuXqsOWHS8MAXZrwMq8Gzw.dGUCCwqzmT4F3dxS0CDPlxQ.sTyMxyKsWr7oeoZdnLZO6dwdNQ8KHo4uONcI2.Kv5o1Drv2lGxOUrMBCSgmilIl1GGVfhbOS5vu02Qir6C22I8Wt7Tq.QgA.CT1W8AuKYCmwxywgB7YTN3aBtRsvUYlxt2CRWSi.xb9SCco7uJwssu8m.dyj_xxxxvMz4u20HqXKEkVVly6gS0```

**Comment by insoxin** [comment]
我收到邮件提醒了,刚想喊你删除. 自己删了,安全意识很不错

第二天可以查看结果,今天试运行如果返回聚合任务成功 大几率已经成了

**Comment by FairyWorld** [comment]
> 等我再加个判断网页状态码的功能, 把返回值,全部显示出来

1. 我把所有任务都点了一遍, 抓取的oYid6CPr填入了paradise里面, 像下面一样。
2. 还不确定有没有运行成功，因为是我手动完成的, 需要下次运行才能确定
3. 但是感觉有点奇怪，我发现软件就运行了10s左右，就结束关闭了，这太快了吧。
4. 后来尝试随便改了个错误的cookie，运行的结果和抓取的cookie一样，都能输出而且内容一样，是否可以加一个日志在cookie失效时提示一下有没真正登录成功

配置如下:
```
{
	"users": [{
			"cookie": "s_fid=000000BD4776B00F-3F2D1BACB3000000",
			"para": "xxx",
			"phone": 123456,
			"monthlybeans": "oYid6CPr=5z4jXLKHElmW1SaKJIRBjDoRyC2W9bltq2fPRsixSVuGePK_TqtxwfmOjnTUhfHXrkEg.DTf9tlaEK1Tkk4QiAM_YGPEXYQ4OtfM9UvW6ntcUVRdjOaTkpmw2GIwUpiQ3YwgZMTnqh9DsDwe0J3bV2FEPV_0aAaJH8NygazYhS8NSVIbLomj5ggX2hXwKVf8bvgGl6xq898TtZIDfSMSwiuGs4I9HGKMoilittzX3oU6VLvWnqEEUqUcshK0Z6RyYdu0hTwdm5FcWaOz.tVa9qmxhQYLMns9QWQmpXu2AdGAZVTOZ60LutiafHByrpPUUJ8ZOpk3XphhzFMYnXuCDua",
			"Paradise": [{
				"setting": "true"
			}, {
				"Polymerize": "oYid6CPr=000000azjNHFP4nSOxjFfoXTl3iMN1wSaKf9Jh.T6oVkQt2GZyt1tX9jteo6kt06TEj4opLgivoJwxoTrpPnqIyo4rpWM5dNbj5cjqcByvQgseD6Ss7837t08qd6Me.23rQySgPhSaBgIBwjkXBIGvJ0yf1ZiOcbmDz7fFcJ6db0iLYd0iKkCvlGdNtHmWjF0T_7J3X5_eYWQv3xSoMDqu47fOhASvInj.Q1dcRWBNPKZdkLsK7arnq0dPc6lDsuQpI7AJKUNWzACV6nLi_wbecrOC0XmQsOqbJjjDou9W0QFfnRQgQsjvxn6B4ZzBGbllnAIpDufohsG2g3m.LvSvJhVZ.UtUgNCfXwQd000000"
			}],
			"systime": "https://cloudflare.api.isoyu.com/time/SysTime/?appCode=B586A14C4EC466D33682F8626CCB3794&auturl=api.isoyu.com&num=13",
			"github": "https://github.com/insoxin/China-Telecom-Helper"

		}

	]
}
```

**Comment by insoxin** [comment]
> > 等我再加个判断网页状态码的功能, 把返回值,全部显示出来
> 
> 1. 我把所有任务都点了一遍, 抓取的oYid6CPr填入了paradise里面, 像下面一样。
> 2. 还不确定有没有运行成功，因为是我手动完成的, 需要下次运行才能确定
> 3. 但是感觉有点奇怪，我发现软件就运行了10s左右，就结束关闭了，这太快了吧。
> 4. 后来尝试随便改了个错误的cookie，运行的结果和抓取的cookie一样，都能输出而且内容一样，是否可以加一个日志在cookie失效时提示一下有没真正登录成功
> 
> 配置如下:
> 
> ```
> {
> 	"users": [{
> 			"cookie": "s_fid=000000BD4776B00F-3F2D1BACB3000000",
> 			"para": "xxx",
> 			"phone": 123456,
> 			"monthlybeans": "oYid6CPr=00000KHElmW1SaKJIRBjDoRyC2W9bltq2fPRsixSVuGePK_TqtxwfmOjnTUhfHXrkEg.DTf9tlaEK1Tkk4QiAM_YGPEXYQ4OtfM9UvW6ntcUVRdjOaTkpmw2GIwUpiQ3YwgZMTnqh9DsDwe0J3bV2FEPV_0aAaJH8NygazYhS8NSVIbLomj5ggX2hXwKVf8bvgGl6xq898TtZIDfSMSwiuGs4I9HGKMoilittzX3oU6VLvWnqEEUqUcshK0Z6RyYdu0hTwdm5FcWaOz.tVa9qmxhQYLMns9QWQmpXu2AdGAZVTOZ60LutiafHByrpPUUJ8ZOpk3XphhzFMYnXuCDua",
> 			"Paradise": [{
> 				"setting": "true"
> 			}, {
> 				"Polymerize": "oYid6CPr=000000azjNHFP4nSOxjFfoXTl3iMN1wSaKf9Jh.T6oVkQt2GZyt1tX9jteo6kt06TEj4opLgivoJwxoTrpPnqIyo4rpWM5dNbj5cjqcByvQgseD6Ss7837t08qd6Me.23rQySgPhSaBgIBwjkXBIGvJ0yf1ZiOcbmDz7fFcJ6db0iLYd0iKkCvlGdNtHmWjF0T_7J3X5_eYWQv3xSoMDqu47fOhASvInj.Q1dcRWBNPKZdkLsK7arnq0dPc6lDsuQpI7AJKUNWzACV6nLi_wbecrOC0XmQsOqbJjjDou9W0QFfnRQgQsjvxn6B4ZzBGbllnAIpDufohsG2g3m.LvSvJhVZ.UtUgNCfXwQd000000"
> 			}],
> 			"systime": "https://cloudflare.api.isoyu.com/time/SysTime/?appCode=B586A14C4EC466D33682F8626CCB3794&auturl=api.isoyu.com&num=13",
> 			"github": "https://github.com/insoxin/China-Telecom-Helper"
> 
> 		}
> 
> 	]
> }
> ```


2.查看是都提示 聚合任务成功....

3.不能吧

4.cookie 作用于 手机号,签到,和创建User-Agent: CtClient;.... 同时绑定IP,模拟常用设备,避免顶号的
金豆任务更多的是para这个值你可以把para改写任意值就会报  解析错误 了

**Comment by kkkkxl** [comment]
![1653031973(1)](https://user-images.githubusercontent.com/37541028/169477120-0f9aefaa-009e-4c7d-852a-bd8d49561106.png)
我也是显示空白的

![1653032016(1)](https://user-images.githubusercontent.com/37541028/169477218-2d95fbee-fe0d-43aa-a69d-1c2a9457a259.png)
paradise的值应该是没问题 抓的时候看了好多遍

**Comment by insoxin** [comment]
> ![1653031973(1)](https://user-images.githubusercontent.com/37541028/169477120-0f9aefaa-009e-4c7d-852a-bd8d49561106.png) 我也是显示空白的
> 
> ![1653032016(1)](https://user-images.githubusercontent.com/37541028/169477218-2d95fbee-fe0d-43aa-a69d-1c2a9457a259.png) paradise的值应该是没问题 抓的时候看了好多遍

新版本已经写好了  新增了网页状态码提醒   正在编译推送

**Comment by kkkkxl** [comment]
> > ![1653031973(1)](https://user-images.githubusercontent.com/37541028/169477120-0f9aefaa-009e-4c7d-852a-bd8d49561106.png) 我也是显示空白的
> > ![1653032016(1)](https://user-images.githubusercontent.com/37541028/169477218-2d95fbee-fe0d-43aa-a69d-1c2a9457a259.png) paradise的值应该是没问题 抓的时候看了好多遍
> 
> 新版本已经写好了 新增了网页状态码提醒 正在编译推送

ok 那我等会用新版本跑一下看看

**Comment by insoxin** [comment]
@kkkkxl paradise的值应该是没问题  你每个消息体返回检查了吗  是不是都
```
{
  "resoultCode": 0,
  "data": {
    "biz": "",
    "code": 0,
    "err": "操作成功"
  },
  "resoultMsg": "聚合任务接口成功"
}

```

这样的返回

**Comment by FairyWorld** [comment]
> 聚合任务成功

聚合任务成功这个没有提示，执行完等了5-6s自动关闭了，还有一个问题是，直播类型的任务好像抓取不了Polymerize, 我用小黄鸟没有搜索到"oYid6CPr", 例如，直播预约，直播点赞，观看15s这些任务

**Comment by insoxin** [comment]
> > 聚合任务成功
> 
> 聚合任务成功这个没有提示，执行完等了5-6s自动关闭了，还有一个问题是，直播类型的任务好像抓取不了Polymerize, 我用小黄鸟没有搜索到"oYid6CPr", 例如，直播预约，直播点赞，观看15s这些任务

你每个消息体返回检查了吗  是不是都
```
{
  "resoultCode": 0,
  "data": {
    "biz": "",
    "code": 0,
    "err": "操作成功"
  },
  "resoultMsg": "聚合任务接口成功"
}

```

这样的返回  如果是这样的返回,那就说明这个加的这个自定义任务是成功的,正确的



直播类型的任务好像抓取不了Polymerize  这个需要全程抓取,跳到第三方的时候做完任务,返回领取.就会出现了

**Comment by kkkkxl** [comment]
> @kkkkxl paradise的值应该是没问题 你每个消息体返回检查了吗 是不是都
> 
> ```
> {
>   "resoultCode": 0,
>   "data": {
>     "biz": "",
>     "code": 0,
>     "err": "操作成功"
>   },
>   "resoultMsg": "聚合任务接口成功"
> }
> ```
> 
> 这样的返回

有一个返回的 聚合任务接口成功  但是 用的0.2的版本 返回的信息还是空白

**Comment by insoxin** [comment]
> > @kkkkxl paradise的值应该是没问题 你每个消息体返回检查了吗 是不是都
> > ```
> > {
> >   "resoultCode": 0,
> >   "data": {
> >     "biz": "",
> >     "code": 0,
> >     "err": "操作成功"
> >   },
> >   "resoultMsg": "聚合任务接口成功"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样的返回
> 
> 有一个返回的 聚合任务接口成功 但是 用的0.2的版本 返回的信息还是空白

给我邮箱insoxin@qq.com 发你config.json配置 文件,我来试试

**Comment by kkkkxl** [comment]
> > > @kkkkxl paradise的值应该是没问题 你每个消息体返回检查了吗 是不是都
> > > ```
> > > {
> > >   "resoultCode": 0,
> > >   "data": {
> > >     "biz": "",
> > >     "code": 0,
> > >     "err": "操作成功"
> > >   },
> > >   "resoultMsg": "聚合任务接口成功"
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 这样的返回
> > 
> > 
> > 有一个返回的 聚合任务接口成功 但是 用的0.2的版本 返回的信息还是空白
> 
> 给我邮箱[insoxin@qq.com](mailto:insoxin@qq.com) 发你config.json配置 文件,我来试试

好的


{
  "resoultCode": 0,
  "data": "{\"biz\":{\"error_desc\":\"发放成功\",\"error_code\":\"0\"},\"code\":0,\"err\":\"发放成功\"}\n",
  "resoultMsg": "领取奖励接口成功"
}
每日登录奖励领取(5金豆),  上面返回的是这个任务的.

**Comment by insoxin** [comment]
@FairyWorld @kkkkxl https://github.com/insoxin/China-Telecom-Helper/releases/tag/v0.3  编译好了0.3版本

**Comment by kkkkxl** [comment]
> @FairyWorld @kkkkxl https://github.com/insoxin/China-Telecom-Helper/releases/tag/v0.3 编译好了0.3版本

我给你发的哪个视频看了吗

**Comment by insoxin** [comment]
> > @FairyWorld @kkkkxl https://github.com/insoxin/China-Telecom-Helper/releases/tag/v0.3 编译好了0.3版本
> 
> 我给你发的哪个视频看了吗

发了吗,没收到最后一条是日志

**Comment by kkkkxl** [comment]
> 

发了 你看下邮箱

**Comment by kkkkxl** [comment]
> > > @FairyWorld @kkkkxl https://github.com/insoxin/China-Telecom-Helper/releases/tag/v0.3 编译好了0.3版本
> > 
> > 
> > 我给你发的哪个视频看了吗
> 
> 发了吗,没收到最后一条是日志

没到到吗

**Comment by kkkkxl** [comment]
> 

嗯,你看下

**Comment by kkkkxl** [comment]
> > > @FairyWorld @kkkkxl https://github.com/insoxin/China-Telecom-Helper/releases/tag/v0.3 编译好了0.3版本
> > 
> > 
> > 我给你发的哪个视频看了吗
> 
> 抱歉漏掉了,我下拉到底看到了

客气了 你看下
