### ISSUE TITLE
来个大佬抓包，分享脚本

### ISSUE THREAD

**Issue by solar24** [insoxin/China-Telecom-Helper#65]
每日分享的+50
有人能抓到这个包吗
或者有知道这个怎么发包
写个脚本就差这个任务了
有成功的联系我，后面写好脚本分享，搞定这个。每天200+豆

**Comment by 521lc21** [comment]
怎么联系

> 每天的+50 人能抓到这个包吗 或者知道这个怎么发包 写个脚本就差这个任务了 有成功的联系我，后面分享写好脚本分享，搞定这个。每天200+豆

**Comment by solar24** [comment]
> 怎么联系
> 
> > 每天的+50 人能抓到这个包吗 或者知道这个怎么发包 写个脚本就差这个任务了 有成功的联系我，后面分享写好脚本分享，搞定这个。每天200+豆

qq475608116

**Comment by limoruirui** [comment]
> 每日分享的+50
> 有人能抓到这个包吗
> 或者有知道这个怎么发包
> 写个脚本就差这个任务了
> 有成功的联系我，后面写好脚本分享，搞定这个。每天200+豆

有个appfuwu.189.cn的 也是有sslpinning的 大概率就是这个包 不过不知道这个包发送的数据需不需要ticket获取
