### ISSUE TITLE
这个还能用吗？

### ISSUE THREAD

**Issue by xxx854** [insoxin/China-Telecom-Helper#66]

**Comment by xxx854** [comment]
写好config.json后运行exe文件，闪退

**Comment by a65101855** [comment]
亲测，闪退一般是哪个步骤出错，你重新弄CONFIG

**Comment by xxx854** [comment]
所以它该怎么弄啊

**Comment by xxx854** [comment]
你在介绍中说活动做不了，是说不能用了吗

**Comment by insoxin** [comment]
> 你在介绍中说活动做不了，是说不能用了吗

![4A682248-765A-46A3-B884-4CF5B5F2DEE8](https://user-images.githubusercontent.com/19371836/176986904-70cf5a49-ddae-43e5-af9a-d9abedc43549.jpeg)


我号黑了,你看我任务都没了

**Comment by xxx854** [comment]
也就是说撸一年，号就黑了，不能玩了是吧

> > 你在介绍中说活动做不了，是说不能用了吗
> 
> ![4A682248-765A-46A3-B884-4CF5B5F2DEE8](https://user-images.githubusercontent.com/19371836/176986904-70cf5a49-ddae-43e5-af9a-d9abedc43549.jpeg)
> 
> 我号黑了,你看我任务都没了

**Comment by insoxin** [comment]
> 也就是说撸一年，号就黑了，不能玩了是吧
> 
> > > 你在介绍中说活动做不了，是说不能用了吗
> > 
> > 
> > ![4A682248-765A-46A3-B884-4CF5B5F2DEE8](https://user-images.githubusercontent.com/19371836/176986904-70cf5a49-ddae-43e5-af9a-d9abedc43549.jpeg)
> > 我号黑了,你看我任务都没了

一月前号黑的,所以说可用性未知  有现实同学挂了半年左右也和我一样.网友也有反馈任务手动无法做,原因未知猜测号黑了

**Comment by xxx854** [comment]
哈，我运行都运行不了

**Comment by xxx854** [comment]
@insoxin

**Comment by rubnet** [comment]
> 号黑的

这个月开始是不是不能换话费了？还是我的号黑了？

**Comment by haohao232323** [comment]
你部署好了吗？可以正常用吗？是不是考虑加混淆参数

**Comment by eon-x** [comment]
读取配置成功之后，获取北京时间闪退

**Comment by insoxin** [comment]
> 读取配置成功之后，获取北京时间闪退

刷新dns
