### ISSUE TITLE
报错panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by zzzddd897** [insoxin/China-Telecom-Helper#7]
正在解析配置文件

Users: 1
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.main()
        /home/runner/work/China-Telecom-Helper/China-Telecom-Helper/main.go:77 +0x3f59

**Comment by insoxin** [comment]
config.json  文件打码后截下图或者发出来更好.我看下   千万记得删除隐私值

**Comment by zzzddd897** [comment]
<img width="816" alt="20220520152012" src="https://user-images.githubusercontent.com/39666548/169474900-51d87023-96f9-45da-850f-1596647eb849.png">

**Comment by zzzddd897** [comment]
<img width="825" alt="微信截图_20220520152203" src="https://user-images.githubusercontent.com/39666548/169475154-4d3107d6-6a1e-4165-a59e-9d617e4dd03d.png">

**Comment by zzzddd897** [comment]
<img width="830" alt="20220520152012" src="https://user-images.githubusercontent.com/39666548/169475586-eca12b0b-50bd-447d-b215-d110faa3fc66.png">

**Comment by insoxin** [comment]
![image](https://user-images.githubusercontent.com/19371836/169475868-e2751060-ac12-4f92-943d-cc802b572912.png)
你看, 你的编辑器都报红了,把这个逗号删除
