### ISSUE TITLE
有个新的抽奖，每个月能抽不少话费，大佬能发开发一下呢

### ISSUE THREAD

**Issue by buse88** [insoxin/China-Telecom-Helper#70]
有个新的抽奖，每个月能抽不少话费，大佬能发开发一下呢

**Comment by insoxin** [comment]
位置在那儿？我没找到

**Comment by buse88** [comment]
电信app首页，星播客 进去直播间有小黄车，小黄车里面不定时有转盘抽奖，每天都能抽到挺多话费的

**Comment by insoxin** [comment]
> 电信app首页，星播客 进去直播间有小黄车，小黄车里面不定时有转盘抽奖，每天都能抽到挺多话费的

不同时间段去看了,观察了两天,难道是假期 不直播了?我没找到,只有普通的

**Comment by buse88** [comment]
有木有啥联系方式，有的时候我发你哈，一个号每个月手动都能撸一些

**Comment by jianhua0209** [comment]
> 

qq:362743904,多谢
