### ISSUE TITLE
config中的systim失效了，无法访问，程序中止。

### ISSUE THREAD

**Issue by lookingtome** [insoxin/China-Telecom-Helper#74]
"systime": "https://api.isoyu.com/time/SysTime/?appCode=B586A14C4EC466D33682F8626CCB3794&auturl=api.isoyu.com&num=13",失效了，无法访问，帮看下吧，另外抓包中的例子，除了para768没变，其它电信都变了，512始终没找到，受累再给指点下，建议加上金豆每月固定兑换，法学大佬的担心，无盈利目的不成立，只是出去学习研究目的做的测试，并让大家24小时删除，你的责任尽了，无需多虑。

**Comment by insoxin** [comment]
我号黑半年多了……没测试环境


![38F549D5-2C2C-4A06-BB18-36267444BFAA](https://user-images.githubusercontent.com/19371836/205213184-8f36e38b-f155-4528-8ccd-72714f548f41.png)

**Comment by gaofeicm** [comment]
> 我号黑半年多了……没测试环境
> 
> ![38F549D5-2C2C-4A06-BB18-36267444BFAA](https://user-images.githubusercontent.com/19371836/205213184-8f36e38b-f155-4528-8ccd-72714f548f41.png)

能否去掉时间验证，或者换个时间api

**Comment by lookingtome** [comment]
程序写死了，去不掉，换了时间验证没用，验证使用了API网站注册，insoxin作者可联系我（Q2391917230），电信我号多，可提供测试.。

**Comment by insoxin** [comment]
> 程序写死了，去不掉，换了时间验证没用，验证使用了API网站注册，insoxin作者可联系我（Q2391917230），电信我号多，可提供测试.。

你刷新一下dns 

试试看

http://cloudflare.api.isoyu.com/ 是否正常
