### ISSUE TITLE
推荐一个好玩并且奖励不错的签到

### ISSUE THREAD

**Issue by jaychoubaby** [insoxin/China-Telecom-Helper#76]

**Comment by CreamK** [comment]
> 微信小程序-巴奴毛肚火锅 ，每天签到可以领取积分，连续签到最大每天可以40积分，积分可以兑换实物礼品，并且礼品的质量非常nice，老哥可以考虑一下，我尝试过qx编写，但是迫于接口加签，无法继续下去

找到sign的计算方法了吗
