### ISSUE TITLE
兑换的参数在哪里设置

### ISSUE THREAD

**Issue by kkkkxl** [insoxin/China-Telecom-Helper#8]
开始800金豆兑换5元话费(每月两次):未找到参数设置,自动跳过
开始400金豆兑换2元话费(每月两次):未找到参数设置,自动跳过
开始200金豆兑换1元话费(每月三次):未找到参数设置,自动跳过
开始200金豆兑换1元话费(每连签七天可兑换一次):未找到参数设置,自动跳过

**Comment by insoxin** [comment]
[China-Telecom-Helper#前言](https://github.com/insoxin/China-Telecom-Helper#%E5%89%8D%E8%A8%80)

**Comment by kkkkxl** [comment]
建议给日志加个时间戳

**Comment by kkkkxl** [comment]
> [China-Telecom-Helper#前言](https://github.com/insoxin/China-Telecom-Helper#%E5%89%8D%E8%A8%80)

建议给日志加个时间戳

**Comment by insoxin** [comment]
> > [China-Telecom-Helper#前言](https://github.com/insoxin/China-Telecom-Helper#%E5%89%8D%E8%A8%80)
> 
> 建议给日志加个时间戳

前面有显示.每一行都加没必要吧,占地方
![image](https://user-images.githubusercontent.com/19371836/169476974-4ca27c3c-000b-4c7e-943d-7c67ac4facf0.png)
n

**Comment by onesixsix** [comment]
老哥，能不能分享一下，现在手动一个话费都抢不到，看了看现在手动用连点器的话电信营业厅APP就不发兑换的包了，一直发https://bigdata-behaviordata.189.cn/behaviordata
