### ISSUE TITLE
在linux下用Crontab来执行会找不到json文件

### ISSUE THREAD

**Issue by VincentCheukwing** [insoxin/China-Telecom-Helper#83]
**描述错误**
在linux下用Crontab来执行会找不到json文件，直接执行则没有问题，能不能加个参数自己写json文件的位置，如果不加就默认当前路径

**软件版本**
v1.0.7

**Comment by lq-259** [comment]
运行命令前先cd

**Comment by insoxin** [comment]
0 0,8,16 * * * cd /root/China-Telecom-Helper_linux_amd64/ && ./China-Telecom-Helper_linux_amd64
