### ISSUE TITLE
v1.0.8 登录失败授权无效

### ISSUE THREAD

**Issue by waterdrops** [insoxin/China-Telecom-Helper#89]
## 下列各问题请注意打码隐藏重要信息

**描述错误**
登录失败，授权无效。

**截图**
![CleanShot 2023-02-13 at 11 51 14](https://user-images.githubusercontent.com/7233747/218366783-565a11d8-66ac-4307-abd2-2a17434c9b89.png)

**软件版本**
v1.0.8
**congfig.json文件配置**
```
{
	"users": [{
		        "AutoUpdate": "false",
			"cookie": "cookie",
			"para": "para",
			"phone": 13800138000,
			"monthlybeans": "monthly beans",
			"Paradise": [{
				"setting": "true"
			}, {
				"Polymerize": "Polymerize"
			}, {
				"Polymerize": "Polymerize"
			}],
			"systime": "http://cloudflare.api.isoyu.com/time/SysTime/?appCode=B586A14C4EC466D33682F8626CCB3794&auturl=api.isoyu.com&num=13",
			"github": "https://github.com/insoxin/China-Telecom-Helper"

		}

	]
}
```

**桌面（请填写以下信息）：**
  - 操作系统：[Debian 11]
  - 版本 [5.10.0-8-amd64  SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux]

**智能手机（请填写以下信息）：**
  - 设备：[iPhone 12 mini]
  - 操作系统：[16.3]

**附加上下文**
升级到V1.0.8 重新抓包后，出现“登录失败,授权无效”

**Comment by insoxin** [comment]
1.0.8使用教程还没写好,退回旧版吧,另外图片建议删除,或打码
