### ISSUE TITLE
没有Linux armv7l 版本的呀！希望加一个！

### ISSUE THREAD

**Issue by JohyC** [insoxin/China-Telecom-Helper#9]
![image](https://user-images.githubusercontent.com/38210128/169479884-a49176f7-f31a-4117-bd8a-049b68d96a04.png)

**Comment by insoxin** [comment]
arm64  能正常执行吗

**Comment by JohyC** [comment]
> arm64 能正常执行吗

不能的。
![image](https://user-images.githubusercontent.com/38210128/169630706-138c226f-d8a2-4de2-ba24-9ca8e0189a13.png)

**Comment by insoxin** [comment]
> > arm64 能正常执行吗
> 
> 不能的。 ![image](https://user-images.githubusercontent.com/38210128/169630706-138c226f-d8a2-4de2-ba24-9ca8e0189a13.png)

chmod +x 了吗

**Comment by JohyC** [comment]
> > > arm64 能正常执行吗
> > 
> > 
> > 不能的。 ![image](https://user-images.githubusercontent.com/38210128/169630706-138c226f-d8a2-4de2-ba24-9ca8e0189a13.png)
> 
> chmod +x 了吗

当然给权限了。。。
哥！这个报错不是明显吗？

exec format error: ./China-Telecom-Helper
格式错误。。

**Comment by insoxin** [comment]
> > > > arm64 能正常执行吗
> > > 
> > > 
> > > 不能的。 ![image](https://user-images.githubusercontent.com/38210128/169630706-138c226f-d8a2-4de2-ba24-9ca8e0189a13.png)
> > 
> > 
> > chmod +x 了吗
> 
> 当然给权限了。。。 哥！这个报错不是明显吗？
> 
> exec format error: ./China-Telecom-Helper 格式错误。。

没遇到啊  我路由器试了可以还以为通用,再去搜索学习去

**Comment by JohyC** [comment]
> > > > > arm64 能正常执行吗
> > > > 
> > > > 
> > > > 不能的。 ![image](https://user-images.githubusercontent.com/38210128/169630706-138c226f-d8a2-4de2-ba24-9ca8e0189a13.png)
> > > 
> > > 
> > > chmod +x 了吗
> > 
> > 
> > 当然给权限了。。。 哥！这个报错不是明显吗？
> > exec format error: ./China-Telecom-Helper 格式错误。。
> 
> 没遇到啊 我路由器试了可以还以为通用,再去搜索学习去

你路由 uname -sm 看看返回的是什么架构呀！

我主要有个 armv7l 架构的小机器很省电，天天转不心疼电费。

**Comment by insoxin** [comment]
> > > > arm64 能正常执行吗
> > > 
> > > 
> > > 不能的。 ![image](https://user-images.githubusercontent.com/38210128/169630706-138c226f-d8a2-4de2-ba24-9ca8e0189a13.png)
> > 
> > 
> > chmod +x 了吗
> 
> 当然给权限了。。。 哥！这个报错不是明显吗？
> 
> exec format error: ./China-Telecom-Helper 格式错误。。

刚搜索回来了  


armv7l is 32 bit processor.

If you need a little bit more information regarding ARMv8, please read @Rinzwind's answer :-)



大佬再试试arm32 ?

**Comment by JohyC** [comment]
> > > > > arm64 能正常执行吗
> > > > 
> > > > 
> > > > 不能的。 ![image](https://user-images.githubusercontent.com/38210128/169630706-138c226f-d8a2-4de2-ba24-9ca8e0189a13.png)
> > > 
> > > 
> > > chmod +x 了吗
> > 
> > 
> > 当然给权限了。。。 哥！这个报错不是明显吗？
> > exec format error: ./China-Telecom-Helper 格式错误。。
> 
> 刚搜索回来了
> 
> armv7l is 32 bit processor.
> 
> If you need a little bit more information regarding ARMv8, please read @Rinzwind's answer :-)
> 
> 大佬再试试arm32 ?

我不是大佬！哥，另外我马上试试！

**Comment by JohyC** [comment]
> > > > > > arm64 能正常执行吗
> > > > > 
> > > > > 
> > > > > 不能的。 ![image](https://user-images.githubusercontent.com/38210128/169630706-138c226f-d8a2-4de2-ba24-9ca8e0189a13.png)
> > > > 
> > > > 
> > > > chmod +x 了吗
> > > 
> > > 
> > > 当然给权限了。。。 哥！这个报错不是明显吗？
> > > exec format error: ./China-Telecom-Helper 格式错误。。
> > 
> > 
> > 刚搜索回来了
> > armv7l is 32 bit processor.
> > If you need a little bit more information regarding ARMv8, please read @Rinzwind's answer :-)
> > 大佬再试试arm32 ?
> 
> 我不是大佬！哥，另外我马上试试！

还是不行呀！
![image](https://user-images.githubusercontent.com/38210128/169631087-adab2e8f-7217-4f5d-b39f-06518cddd138.png)

**Comment by insoxin** [comment]
> > > > > > arm64 能正常执行吗
> > > > > 
> > > > > 
> > > > > 不能的。 ![image](https://user-images.githubusercontent.com/38210128/169630706-138c226f-d8a2-4de2-ba24-9ca8e0189a13.png)
> > > > 
> > > > 
> > > > chmod +x 了吗
> > > 
> > > 
> > > 当然给权限了。。。 哥！这个报错不是明显吗？
> > > exec format error: ./China-Telecom-Helper 格式错误。。
> > 
> > 
> > 刚搜索回来了
> > armv7l is 32 bit processor.
> > If you need a little bit more information regarding ARMv8, please read @Rinzwind's answer :-)
> > 大佬再试试arm32 ?
> 
> 我不是大佬！哥，另外我马上试试！

**Comment by insoxin** [comment]
> > > > > > > arm64 能正常执行吗
> > > > > > 
> > > > > > 
> > > > > > 不能的。 ![image](https://user-images.githubusercontent.com/38210128/169630706-138c226f-d8a2-4de2-ba24-9ca8e0189a13.png)
> > > > > 
> > > > > 
> > > > > chmod +x 了吗
> > > > 
> > > > 
> > > > 当然给权限了。。。 哥！这个报错不是明显吗？
> > > > exec format error: ./China-Telecom-Helper 格式错误。。
> > > 
> > > 
> > > 刚搜索回来了
> > > armv7l is 32 bit processor.
> > > If you need a little bit more information regarding ARMv8, please read @Rinzwind's answer :-)
> > > 大佬再试试arm32 ?
> > 
> > 
> > 我不是大佬！哥，另外我马上试试！
> 
> 还是不行呀！ ![image](https://user-images.githubusercontent.com/38210128/169631087-adab2e8f-7217-4f5d-b39f-06518cddd138.png)

大佬多等一会儿,我扔在搜索

**Comment by insoxin** [comment]
@ 大佬  方便截图一下这个行命令返回值吗
```
grep -i vfp /proc/cpuinfo
```

**Comment by JohyC** [comment]
> @ 大佬 方便截图一下这行命令返回值吗
> 
> ```
> grep -i vfp /proc/cpuinfo
> ```

![image](https://user-images.githubusercontent.com/38210128/169631367-14cf45e2-0217-4e65-aacb-c5322a320c28.png)

**Comment by JohyC** [comment]
> @ 大佬 方便截图一下这行命令返回值吗
> 
> ```
> grep -i vfp /proc/cpuinfo
> ```

咱们这个是用golang写的吗？
GOARCH=arm GOARM=7
如果是的话，用这个环境变量交叉编译就ok了！

**Comment by insoxin** [comment]
> > @ 大佬 方便截图一下这行命令返回值吗
> > ```
> > grep -i vfp /proc/cpuinfo
> > ```
> 
> 咱们这个是用golang写的吗？ GOARCH=arm GOARM=7 如果是的话，用这个环境变量交叉编译就ok了！

对  编译好了  在上传了 稍等

**Comment by JohyC** [comment]
> > > @ 大佬 方便截图一下这行命令返回值吗
> > > ```
> > > grep -i vfp /proc/cpuinfo
> > > ```
> > 
> > 
> > 咱们这个是用golang写的吗？ GOARCH=arm GOARM=7 如果是的话，用这个环境变量交叉编译就ok了！
> 
> 对 编译好了 在上传了 稍等

ok！期待中。

**Comment by insoxin** [comment]
> > > > @ 大佬 方便截图一下这行命令返回值吗
> > > > ```
> > > > grep -i vfp /proc/cpuinfo
> > > > ```
> > > 
> > > 
> > > 咱们这个是用golang写的吗？ GOARCH=arm GOARM=7 如果是的话，用这个环境变量交叉编译就ok了！
> > 
> > 
> > 对 编译好了 在上传了 稍等
> 
> ok！期待中。

https://github.com/insoxin/China-Telecom-Helper/releases/download/0.1/China-Telecom-Helper

大佬试试看

**Comment by JohyC** [comment]
> > > > > @ 大佬 方便截图一下这行命令返回值吗
> > > > > ```
> > > > > grep -i vfp /proc/cpuinfo
> > > > > ```
> > > > 
> > > > 
> > > > 咱们这个是用golang写的吗？ GOARCH=arm GOARM=7 如果是的话，用这个环境变量交叉编译就ok了！
> > > 
> > > 
> > > 对 编译好了 在上传了 稍等
> > 
> > 
> > ok！期待中。
> 
> https://github.com/insoxin/China-Telecom-Helper/releases/download/0.1/China-Telecom-Helper
> 
> 大佬试试看

ok了！终于可以用了。🤣🤣🤣

**Comment by insoxin** [comment]
> > > > > > @ 大佬 方便截图一下这行命令返回值吗
> > > > > > ```
> > > > > > grep -i vfp /proc/cpuinfo
> > > > > > ```
> > > > > 
> > > > > 
> > > > > 咱们这个是用golang写的吗？ GOARCH=arm GOARM=7 如果是的话，用这个环境变量交叉编译就ok了！
> > > > 
> > > > 
> > > > 对 编译好了 在上传了 稍等
> > > 
> > > 
> > > ok！期待中。
> > 
> > 
> > https://github.com/insoxin/China-Telecom-Helper/releases/download/0.1/China-Telecom-Helper
> > 大佬试试看
> 
> ok了！终于可以用了。🤣🤣🤣谢谢大佬的工具！！！

没没没,我菜鸡,今天才知道armv7l属于32位

**Comment by JohyC** [comment]
> > > > > > > @ 大佬 方便截图一下这行命令返回值吗
> > > > > > > ```
> > > > > > > grep -i vfp /proc/cpuinfo
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > 咱们这个是用golang写的吗？ GOARCH=arm GOARM=7 如果是的话，用这个环境变量交叉编译就ok了！
> > > > > 
> > > > > 
> > > > > 对 编译好了 在上传了 稍等
> > > > 
> > > > 
> > > > ok！期待中。
> > > 
> > > 
> > > https://github.com/insoxin/China-Telecom-Helper/releases/download/0.1/China-Telecom-Helper
> > > 大佬试试看
> > 
> > 
> > ok了！终于可以用了。🤣🤣🤣谢谢大佬的工具！！！
> 
> 没没没,我菜鸡,今天才知道armv7l属于32位

👍👍👍

**Comment by insoxin** [comment]
@[JohyC](https://github.com/JohyC) 新版,我编译了20个不同系统版本,以后也会按这个
