### ISSUE TITLE
./China-Telecom-Helper_linux_mips64: line 1: syntax error: unexpected "("

### ISSUE THREAD

**Issue by rm-f1024** [insoxin/China-Telecom-Helper#98]
## 下列各问题请注意打码隐藏重要信息

**描述错误**
我在执行./China-Telecom-Helper_linux_mips64文件的时候,
系统报错line 1: syntax error: unexpected "("
我的Cpu架构是mips的 系统环境也是mips  为什么不可以用呢
同级目录下有congfig.json文件

3. 向下滚动到“....”
4.查看错误

**预期行为**
我希望能正常运行

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
**软件版本**
v1.0.0
**congfig.json文件配置**
```
{
	"users": [{
		        "AutoUpdate": "false",
			"cookie": "cookie",
			"para": "para",
			"phone": 13800138000,
			"monthlybeans": "monthly beans",
			"Paradise": [{
				"setting": "true"
			}, {
				"Polymerize": "Polymerize"
			}, {
				"Polymerize": "Polymerize"
			}],
			"systime": "http://cloudflare.api.isoyu.com/time/SysTime/?appCode=B586A14C4EC466D33682F8626CCB3794&auturl=api.isoyu.com&num=13",
			"github": "https://github.com/insoxin/China-Telecom-Helper"

		}

	]
}
```

**桌面（请填写以下信息）：**
  - 操作系统：openwrt的17.01版本
 

**智能手机（请填写以下信息）：**
  - 设备：[例如 iPhone 6]
  - 操作系统：[例如 iOS8.1]
  - 浏览器 [例如 chrome, safari]
  - 版本 [例如 22]

**附加上下文**
在此处添加有关该问题的任何其他上下文。

**Comment by insoxin** [comment]
新版你可以了吗？

**Comment by rm-f1024** [comment]
> 新版你可以了吗？

刚刚试了一下 好像不行
![image](https://user-images.githubusercontent.com/57568495/224479232-d143a52e-c7c7-4f32-9588-35ed207ce7e1.png)

**Comment by insoxin** [comment]
$ bash linux_mips64

   或

   $ sh linux_mips64



试试

**Comment by rm-f1024** [comment]
也不行
![image](https://user-images.githubusercontent.com/57568495/224479581-fde66071-7a36-436b-9feb-367511318c10.png)

**Comment by insoxin** [comment]
> 也不行
> ![image](https://user-images.githubusercontent.com/57568495/224479581-fde66071-7a36-436b-9feb-367511318c10.png)
 我再搜搜去

**Comment by insoxin** [comment]
问了群友,有人说你可能下错了版本



https://github.com/insoxin/China-Telecom-Helper/releases/download/1.0.12/China-Telecom-Helper_linux_mips64le.tar.gz


这个试试?

**Comment by rm-f1024** [comment]
![image](https://user-images.githubusercontent.com/57568495/224481967-236ea4ee-c03f-43a9-b5ea-9bfb5e0897a3.png)
现在是这样的错误
